// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "runQueue.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic runQueue::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic runQueue::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> runQueue::ap_ST_st1_fsm_0 = "00000";
const sc_lv<5> runQueue::ap_ST_st2_fsm_1 = "1";
const sc_lv<5> runQueue::ap_ST_st3_fsm_2 = "10";
const sc_lv<5> runQueue::ap_ST_st4_fsm_3 = "11";
const sc_lv<5> runQueue::ap_ST_st5_fsm_4 = "100";
const sc_lv<5> runQueue::ap_ST_st6_fsm_5 = "101";
const sc_lv<5> runQueue::ap_ST_st7_fsm_6 = "110";
const sc_lv<5> runQueue::ap_ST_st8_fsm_7 = "111";
const sc_lv<5> runQueue::ap_ST_st9_fsm_8 = "1000";
const sc_lv<5> runQueue::ap_ST_st10_fsm_9 = "1001";
const sc_lv<5> runQueue::ap_ST_st11_fsm_10 = "1010";
const sc_lv<5> runQueue::ap_ST_st12_fsm_11 = "1011";
const sc_lv<5> runQueue::ap_ST_st13_fsm_12 = "1100";
const sc_lv<5> runQueue::ap_ST_st14_fsm_13 = "1101";
const sc_lv<5> runQueue::ap_ST_st15_fsm_14 = "1110";
const sc_lv<5> runQueue::ap_ST_st16_fsm_15 = "1111";
const sc_lv<5> runQueue::ap_ST_st17_fsm_16 = "10000";
const sc_lv<5> runQueue::ap_ST_st18_fsm_17 = "10001";
const sc_lv<5> runQueue::ap_ST_st19_fsm_18 = "10010";
const sc_lv<5> runQueue::ap_ST_st20_fsm_19 = "10011";
const sc_lv<5> runQueue::ap_ST_st21_fsm_20 = "10100";
const sc_lv<5> runQueue::ap_ST_st22_fsm_21 = "10101";
const sc_lv<5> runQueue::ap_ST_st23_fsm_22 = "10110";
const sc_lv<5> runQueue::ap_ST_st24_fsm_23 = "10111";
const sc_lv<1> runQueue::ap_const_lv1_0 = "0";
const sc_lv<1> runQueue::ap_const_lv1_1 = "1";
const sc_lv<32> runQueue::ap_const_lv32_1 = "1";
const sc_lv<4> runQueue::ap_const_lv4_0 = "0000";
const sc_lv<32> runQueue::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<4> runQueue::ap_const_lv4_5 = "101";
const sc_lv<2> runQueue::ap_const_lv2_1 = "1";
const sc_lv<2> runQueue::ap_const_lv2_0 = "00";
const sc_lv<2> runQueue::ap_const_lv2_2 = "10";

runQueue::runQueue(sc_module_name name) : sc_module(name), mVcdFile(0) {
    random_priorities_U = new runQueue_random_priorities("random_priorities_U");
    random_priorities_U->clk(ap_clk);
    random_priorities_U->reset(ap_rst);
    random_priorities_U->address0(random_priorities_address0);
    random_priorities_U->ce0(random_priorities_ce0);
    random_priorities_U->q0(random_priorities_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm );
    sensitive << ( j_phi_fu_172_p4 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm );
    sensitive << ( j_phi_fu_172_p4 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm );
    sensitive << ( j_phi_fu_172_p4 );
    sensitive << ( result_fu_80 );

    SC_METHOD(thread_cmdOut_V);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_load_fu_277_p1 );
    sensitive << ( localFull_load_reg_463 );
    sensitive << ( grp_load_fu_288_p1 );
    sensitive << ( localEmpty_load_2_reg_480 );
    sensitive << ( localFull_load_3_reg_484 );
    sensitive << ( localEmpty_load_reg_496 );
    sensitive << ( localFull_load_4_reg_514 );
    sensitive << ( localFull_load_1_reg_526 );
    sensitive << ( cmdOut_V_preg );

    SC_METHOD(thread_currentPriority_V);
    sensitive << ( ap_CS_fsm );
    sensitive << ( priorityIn_V );
    sensitive << ( tmp_reg2mem_reg_191 );
    sensitive << ( tmp_6_reg2mem_reg_238 );
    sensitive << ( currentPriority_V_preg );

    SC_METHOD(thread_empty_read_read_fu_110_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( empty );

    SC_METHOD(thread_fullOut);
    sensitive << ( ap_CS_fsm );
    sensitive << ( full_assign_fu_92 );
    sensitive << ( fullOut_preg );

    SC_METHOD(thread_full_read_read_fu_104_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( full );

    SC_METHOD(thread_grp_fu_291_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( last_1_reg_446 );
    sensitive << ( last_load_reg_458 );
    sensitive << ( localFull_load_reg_463 );
    sensitive << ( grp_load_fu_288_p1 );
    sensitive << ( localEmpty_load_2_reg_480 );
    sensitive << ( localFull_load_3_reg_484 );
    sensitive << ( localEmpty_load_reg_496 );
    sensitive << ( localFull_load_4_reg_514 );
    sensitive << ( localFull_load_1_reg_526 );

    SC_METHOD(thread_grp_fu_295_p2);
    sensitive << ( grp_fu_291_p2 );

    SC_METHOD(thread_grp_fu_301_p2);
    sensitive << ( result_load_reg_453 );
    sensitive << ( grp_fu_295_p2 );

    SC_METHOD(thread_grp_load_fu_277_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( localFull_fu_96 );

    SC_METHOD(thread_grp_load_fu_288_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( localFull_load_reg_463 );
    sensitive << ( localEmpty_load_2_reg_480 );
    sensitive << ( localFull_load_3_reg_484 );
    sensitive << ( localEmpty_load_reg_496 );
    sensitive << ( localFull_load_4_reg_514 );
    sensitive << ( localFull_load_1_reg_526 );
    sensitive << ( localEmpty_fu_100 );

    SC_METHOD(thread_i8_fu_337_p2);
    sensitive << ( i_reg2mem_reg_180 );

    SC_METHOD(thread_i_1_fu_371_p2);
    sensitive << ( i_3_reg2mem_reg_227 );

    SC_METHOD(thread_i_s_fu_360_p2);
    sensitive << ( i_1_reg2mem_reg_214 );

    SC_METHOD(thread_j_phi_fu_172_p4);
    sensitive << ( j_reg_167 );

    SC_METHOD(thread_last_1_fu_320_p1);
    sensitive << ( priorityIn_V );

    SC_METHOD(thread_p_result_2_fu_366_p2);
    sensitive << ( result_1_s_reg_500 );
    sensitive << ( grp_fu_295_p2 );

    SC_METHOD(thread_p_result_3_fu_387_p2);
    sensitive << ( result_load_2_reg_530 );
    sensitive << ( grp_fu_295_p2 );

    SC_METHOD(thread_priorityOut_V);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_load_fu_277_p1 );
    sensitive << ( tmp_fu_343_p1 );
    sensitive << ( tmp_1_fu_382_p1 );
    sensitive << ( priorityOut_V_preg );

    SC_METHOD(thread_random_priorities_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_s_fu_377_p1 );

    SC_METHOD(thread_random_priorities_ce0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_result_1_s_fu_353_p2);
    sensitive << ( result_fu_80 );
    sensitive << ( tmp_3_fu_348_p2 );

    SC_METHOD(thread_tmp_1_fu_382_p1);
    sensitive << ( random_priorities_q0 );

    SC_METHOD(thread_tmp_3_fu_348_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( last_1_reg_446 );
    sensitive << ( op2_assign_reg2mem_reg_203 );

    SC_METHOD(thread_tmp_fu_343_p1);
    sensitive << ( i_reg2mem_reg_180 );

    SC_METHOD(thread_tmp_s_fu_377_p1);
    sensitive << ( i_3_reg2mem_reg_227 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_load_fu_277_p1 );
    sensitive << ( localFull_load_reg_463 );
    sensitive << ( grp_load_fu_288_p1 );
    sensitive << ( localEmpty_load_2_reg_480 );
    sensitive << ( localFull_load_3_reg_484 );
    sensitive << ( localEmpty_load_reg_496 );
    sensitive << ( localFull_load_4_reg_514 );
    sensitive << ( localFull_load_1_reg_526 );
    sensitive << ( j_phi_fu_172_p4 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "00000";
    cmdOut_V_preg = "00";
    priorityOut_V_preg = "0000";
    fullOut_preg = SC_LOGIC_0;
    currentPriority_V_preg = "0000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "runQueue_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, priorityOut_V, "(port)priorityOut_V");
    sc_trace(mVcdFile, priorityIn_V, "(port)priorityIn_V");
    sc_trace(mVcdFile, cmdOut_V, "(port)cmdOut_V");
    sc_trace(mVcdFile, empty, "(port)empty");
    sc_trace(mVcdFile, full, "(port)full");
    sc_trace(mVcdFile, currentPriority_V, "(port)currentPriority_V");
    sc_trace(mVcdFile, fullOut, "(port)fullOut");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, random_priorities_address0, "random_priorities_address0");
    sc_trace(mVcdFile, random_priorities_ce0, "random_priorities_ce0");
    sc_trace(mVcdFile, random_priorities_q0, "random_priorities_q0");
    sc_trace(mVcdFile, last_1_fu_320_p1, "last_1_fu_320_p1");
    sc_trace(mVcdFile, last_1_reg_446, "last_1_reg_446");
    sc_trace(mVcdFile, result_load_reg_453, "result_load_reg_453");
    sc_trace(mVcdFile, last_load_reg_458, "last_load_reg_458");
    sc_trace(mVcdFile, grp_load_fu_277_p1, "grp_load_fu_277_p1");
    sc_trace(mVcdFile, localFull_load_reg_463, "localFull_load_reg_463");
    sc_trace(mVcdFile, i8_fu_337_p2, "i8_fu_337_p2");
    sc_trace(mVcdFile, tmp_fu_343_p1, "tmp_fu_343_p1");
    sc_trace(mVcdFile, grp_load_fu_288_p1, "grp_load_fu_288_p1");
    sc_trace(mVcdFile, localEmpty_load_2_reg_480, "localEmpty_load_2_reg_480");
    sc_trace(mVcdFile, localFull_load_3_reg_484, "localFull_load_3_reg_484");
    sc_trace(mVcdFile, grp_fu_301_p2, "grp_fu_301_p2");
    sc_trace(mVcdFile, localEmpty_load_reg_496, "localEmpty_load_reg_496");
    sc_trace(mVcdFile, result_1_s_fu_353_p2, "result_1_s_fu_353_p2");
    sc_trace(mVcdFile, result_1_s_reg_500, "result_1_s_reg_500");
    sc_trace(mVcdFile, i_s_fu_360_p2, "i_s_fu_360_p2");
    sc_trace(mVcdFile, localFull_load_4_reg_514, "localFull_load_4_reg_514");
    sc_trace(mVcdFile, p_result_2_fu_366_p2, "p_result_2_fu_366_p2");
    sc_trace(mVcdFile, localFull_load_1_reg_526, "localFull_load_1_reg_526");
    sc_trace(mVcdFile, result_load_2_reg_530, "result_load_2_reg_530");
    sc_trace(mVcdFile, i_1_fu_371_p2, "i_1_fu_371_p2");
    sc_trace(mVcdFile, i_1_reg_538, "i_1_reg_538");
    sc_trace(mVcdFile, tmp_1_fu_382_p1, "tmp_1_fu_382_p1");
    sc_trace(mVcdFile, j_phi_fu_172_p4, "j_phi_fu_172_p4");
    sc_trace(mVcdFile, j_reg_167, "j_reg_167");
    sc_trace(mVcdFile, i_reg2mem_reg_180, "i_reg2mem_reg_180");
    sc_trace(mVcdFile, tmp_reg2mem_reg_191, "tmp_reg2mem_reg_191");
    sc_trace(mVcdFile, op2_assign_reg2mem_reg_203, "op2_assign_reg2mem_reg_203");
    sc_trace(mVcdFile, i_1_reg2mem_reg_214, "i_1_reg2mem_reg_214");
    sc_trace(mVcdFile, i_3_reg2mem_reg_227, "i_3_reg2mem_reg_227");
    sc_trace(mVcdFile, tmp_6_reg2mem_reg_238, "tmp_6_reg2mem_reg_238");
    sc_trace(mVcdFile, p_result_3_reg2mem_0_ph_reg_250, "p_result_3_reg2mem_0_ph_reg_250");
    sc_trace(mVcdFile, p_result_3_fu_387_p2, "p_result_3_fu_387_p2");
    sc_trace(mVcdFile, tmp_s_fu_377_p1, "tmp_s_fu_377_p1");
    sc_trace(mVcdFile, result_fu_80, "result_fu_80");
    sc_trace(mVcdFile, last_fu_84, "last_fu_84");
    sc_trace(mVcdFile, empty_assign_fu_88, "empty_assign_fu_88");
    sc_trace(mVcdFile, empty_read_read_fu_110_p2, "empty_read_read_fu_110_p2");
    sc_trace(mVcdFile, full_assign_fu_92, "full_assign_fu_92");
    sc_trace(mVcdFile, full_read_read_fu_104_p2, "full_read_read_fu_104_p2");
    sc_trace(mVcdFile, localFull_fu_96, "localFull_fu_96");
    sc_trace(mVcdFile, localEmpty_fu_100, "localEmpty_fu_100");
    sc_trace(mVcdFile, cmdOut_V_preg, "cmdOut_V_preg");
    sc_trace(mVcdFile, priorityOut_V_preg, "priorityOut_V_preg");
    sc_trace(mVcdFile, fullOut_preg, "fullOut_preg");
    sc_trace(mVcdFile, currentPriority_V_preg, "currentPriority_V_preg");
    sc_trace(mVcdFile, grp_fu_291_p2, "grp_fu_291_p2");
    sc_trace(mVcdFile, grp_fu_295_p2, "grp_fu_295_p2");
    sc_trace(mVcdFile, tmp_3_fu_348_p2, "tmp_3_fu_348_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("runQueue.hdltvin.dat");
    mHdltvoutHandle.open("runQueue.hdltvout.dat");
}

runQueue::~runQueue() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete random_priorities_U;
}

void runQueue::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        cmdOut_V_preg = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,5,5>(ap_ST_st9_fsm_8, ap_CS_fsm.read()) && 
              esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || 
             (esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
              esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read())) || 
             (esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
              esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read())) || 
             (esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
              esl_seteq<1,5,5>(ap_ST_st12_fsm_11, ap_CS_fsm.read())) || 
             (esl_seteq<1,5,5>(ap_ST_st20_fsm_19, ap_CS_fsm.read()) && 
              ((esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_2_reg_480.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_4_reg_514.read())) || 
               (esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_2_reg_480.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_3_reg_484.read())) || 
               (esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
                !esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_4_reg_514.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_reg_496.read())) || 
               (esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
                !esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_reg_496.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_1_reg_526.read())))) || 
             (esl_seteq<1,5,5>(ap_ST_st7_fsm_6, ap_CS_fsm.read()) && 
              esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
              esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || 
             (esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
              esl_seteq<1,5,5>(ap_ST_st10_fsm_9, ap_CS_fsm.read())) || 
             (esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
              esl_seteq<1,5,5>(ap_ST_st23_fsm_22, ap_CS_fsm.read())))) {
            cmdOut_V_preg = ap_const_lv2_2;
        } else if (((esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read()) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || 
                    (!esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
                     esl_seteq<1,5,5>(ap_ST_st23_fsm_22, ap_CS_fsm.read())) || 
                    (esl_seteq<1,5,5>(ap_ST_st3_fsm_2, ap_CS_fsm.read()) && 
                     !esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || 
                    (esl_seteq<1,5,5>(ap_ST_st6_fsm_5, ap_CS_fsm.read()) && 
                     !esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || 
                    (esl_seteq<1,5,5>(ap_ST_st8_fsm_7, ap_CS_fsm.read()) && 
                     !esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || 
                    (esl_seteq<1,5,5>(ap_ST_st13_fsm_12, ap_CS_fsm.read()) && 
                     !esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || 
                    (esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read()) && 
                     !esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || 
                    (esl_seteq<1,5,5>(ap_ST_st18_fsm_17, ap_CS_fsm.read()) && 
                     !esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || 
                    (esl_seteq<1,5,5>(ap_ST_st7_fsm_6, ap_CS_fsm.read()) && 
                     esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || 
                    (esl_seteq<1,5,5>(ap_ST_st10_fsm_9, ap_CS_fsm.read()) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || 
                    (esl_seteq<1,5,5>(ap_ST_st12_fsm_11, ap_CS_fsm.read()) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || 
                    (esl_seteq<1,5,5>(ap_ST_st9_fsm_8, ap_CS_fsm.read()) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || 
                    (esl_seteq<1,5,5>(ap_ST_st20_fsm_19, ap_CS_fsm.read()) && 
                     ((esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
                       esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_2_reg_480.read()) && 
                       esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_4_reg_514.read()) && 
                       !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || 
                      (esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
                       !esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_2_reg_480.read()) && 
                       esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_3_reg_484.read()) && 
                       !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || 
                      (!esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
                       esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_4_reg_514.read()) && 
                       esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_reg_496.read()) && 
                       !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || 
                      (!esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
                       !esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_reg_496.read()) && 
                       esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_1_reg_526.read()) && 
                       !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())))) || 
                    (esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read()) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())))) {
            cmdOut_V_preg = ap_const_lv2_0;
        } else if (((esl_seteq<1,5,5>(ap_ST_st6_fsm_5, ap_CS_fsm.read()) && 
                     esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || 
                    esl_seteq<1,5,5>(ap_ST_st19_fsm_18, ap_CS_fsm.read()) || 
                    (esl_seteq<1,5,5>(ap_ST_st3_fsm_2, ap_CS_fsm.read()) && 
                     esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || 
                    (esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0) && 
                     esl_seteq<1,5,5>(ap_ST_st13_fsm_12, ap_CS_fsm.read())) || 
                    (esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0) && 
                     esl_seteq<1,5,5>(ap_ST_st8_fsm_7, ap_CS_fsm.read())) || 
                    (esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0) && 
                     esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read())))) {
            cmdOut_V_preg = ap_const_lv2_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        currentPriority_V_preg = ap_const_lv4_0;
    } else {
        if (esl_seteq<1,5,5>(ap_ST_st18_fsm_17, ap_CS_fsm.read())) {
            currentPriority_V_preg = tmp_6_reg2mem_reg_238.read();
        } else if ((esl_seteq<1,5,5>(ap_ST_st12_fsm_11, ap_CS_fsm.read()) || 
                    esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()))) {
            currentPriority_V_preg = priorityIn_V.read();
        } else if (esl_seteq<1,5,5>(ap_ST_st6_fsm_5, ap_CS_fsm.read())) {
            currentPriority_V_preg = tmp_reg2mem_reg_191.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        fullOut_preg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,5,5>(ap_ST_st4_fsm_3, ap_CS_fsm.read())) {
            fullOut_preg =  (sc_logic) (full_assign_fu_92.read()[0]);
        }
    }
    if ((esl_seteq<1,5,5>(ap_ST_st7_fsm_6, ap_CS_fsm.read()) && 
         (esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) || 
          !esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0)))) {
        i_1_reg2mem_reg_214 = ap_const_lv32_1;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
                esl_seteq<1,5,5>(ap_ST_st12_fsm_11, ap_CS_fsm.read()))) {
        i_1_reg2mem_reg_214 = i_s_fu_360_p2.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st16_fsm_15, ap_CS_fsm.read())) {
        i_3_reg2mem_reg_227 = ap_const_lv32_1;
    } else if (esl_seteq<1,5,5>(ap_ST_st19_fsm_18, ap_CS_fsm.read())) {
        i_3_reg2mem_reg_227 = i_1_reg_538.read();
    }
    if (esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) {
        if (esl_seteq<1,5,5>(ap_ST_st6_fsm_5, ap_CS_fsm.read())) {
            i_reg2mem_reg_180 = i8_fu_337_p2.read();
        } else if (esl_seteq<1,5,5>(ap_ST_st3_fsm_2, ap_CS_fsm.read())) {
            i_reg2mem_reg_180 = ap_const_lv32_1;
        }
    }
    if (esl_seteq<1,5,5>(ap_ST_st24_fsm_23, ap_CS_fsm.read())) {
        j_reg_167 = ap_const_lv1_1;
    } else if ((esl_seteq<1,5,5>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        j_reg_167 = ap_const_lv1_0;
    }
    if ((!esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
         esl_seteq<1,5,5>(ap_ST_st23_fsm_22, ap_CS_fsm.read()))) {
        last_fu_84 = last_1_reg_446.read();
    } else if ((esl_seteq<1,5,5>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        last_fu_84 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,5,5>(ap_ST_st7_fsm_6, ap_CS_fsm.read()) && 
         (esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) || 
          !esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0)))) {
        op2_assign_reg2mem_reg_203 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
                esl_seteq<1,5,5>(ap_ST_st12_fsm_11, ap_CS_fsm.read()))) {
        op2_assign_reg2mem_reg_203 = i_1_reg2mem_reg_214.read();
    }
    if ((esl_seteq<1,5,5>(ap_ST_st20_fsm_19, ap_CS_fsm.read()) && 
         ((esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
           esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
           esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_2_reg_480.read()) && 
           esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_4_reg_514.read())) || 
          (esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
           esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
           !esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_2_reg_480.read()) && 
           esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_3_reg_484.read())) || 
          (esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
           !esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
           esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_4_reg_514.read()) && 
           esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_reg_496.read())) || 
          (esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
           !esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
           !esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_reg_496.read()) && 
           esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_1_reg_526.read()))))) {
        p_result_3_reg2mem_0_ph_reg_250 = p_result_3_fu_387_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
                esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read()))) {
        p_result_3_reg2mem_0_ph_reg_250 = p_result_2_fu_366_p2.read();
    } else if (((esl_seteq<1,5,5>(ap_ST_st9_fsm_8, ap_CS_fsm.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || 
                (esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
                 esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read())))) {
        p_result_3_reg2mem_0_ph_reg_250 = grp_fu_301_p2.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        priorityOut_V_preg = ap_const_lv4_0;
    } else {
        if (esl_seteq<1,5,5>(ap_ST_st19_fsm_18, ap_CS_fsm.read())) {
            priorityOut_V_preg = tmp_1_fu_382_p1.read();
        } else if (((esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0) && 
                     esl_seteq<1,5,5>(ap_ST_st13_fsm_12, ap_CS_fsm.read())) || 
                    (esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0) && 
                     esl_seteq<1,5,5>(ap_ST_st8_fsm_7, ap_CS_fsm.read())) || 
                    (esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0) && 
                     esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read())))) {
            priorityOut_V_preg = ap_const_lv4_5;
        } else if ((esl_seteq<1,5,5>(ap_ST_st6_fsm_5, ap_CS_fsm.read()) && 
                    esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0))) {
            priorityOut_V_preg = tmp_fu_343_p1.read();
        } else if ((esl_seteq<1,5,5>(ap_ST_st3_fsm_2, ap_CS_fsm.read()) && 
                    esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0))) {
            priorityOut_V_preg = ap_const_lv4_0;
        }
    }
    if ((!esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
         esl_seteq<1,5,5>(ap_ST_st23_fsm_22, ap_CS_fsm.read()))) {
        result_fu_80 = p_result_3_reg2mem_0_ph_reg_250.read();
    } else if (((esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0) && 
                 esl_seteq<1,5,5>(ap_ST_st13_fsm_12, ap_CS_fsm.read())) || 
                (esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())))) {
        result_fu_80 = result_1_s_reg_500.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
                esl_seteq<1,5,5>(ap_ST_st12_fsm_11, ap_CS_fsm.read()))) {
        result_fu_80 = result_1_s_fu_353_p2.read();
    } else if ((esl_seteq<1,5,5>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        result_fu_80 = ap_const_lv1_1;
    }
    if (esl_seteq<1,5,5>(ap_ST_st16_fsm_15, ap_CS_fsm.read())) {
        tmp_6_reg2mem_reg_238 = ap_const_lv4_5;
    } else if (esl_seteq<1,5,5>(ap_ST_st19_fsm_18, ap_CS_fsm.read())) {
        tmp_6_reg2mem_reg_238 = tmp_1_fu_382_p1.read();
    }
    if (esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) {
        if (esl_seteq<1,5,5>(ap_ST_st6_fsm_5, ap_CS_fsm.read())) {
            tmp_reg2mem_reg_191 = tmp_fu_343_p1.read();
        } else if (esl_seteq<1,5,5>(ap_ST_st3_fsm_2, ap_CS_fsm.read())) {
            tmp_reg2mem_reg_191 = ap_const_lv4_0;
        }
    }
    if ((esl_seteq<1,5,5>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        empty_assign_fu_88 = empty_read_read_fu_110_p2.read();
        full_assign_fu_92 = full_read_read_fu_104_p2.read();
        last_1_reg_446 = last_1_fu_320_p1.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st18_fsm_17, ap_CS_fsm.read())) {
        i_1_reg_538 = i_1_fu_371_p2.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        last_load_reg_458 = last_fu_84.read();
        result_load_reg_453 = result_fu_80.read();
    }
    if (((esl_seteq<1,5,5>(ap_ST_st3_fsm_2, ap_CS_fsm.read()) && 
  !esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || (esl_seteq<1,5,5>(ap_ST_st6_fsm_5, ap_CS_fsm.read()) && 
  !esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || (esl_seteq<1,5,5>(ap_ST_st8_fsm_7, ap_CS_fsm.read()) && 
  !esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || esl_seteq<1,5,5>(ap_ST_st11_fsm_10, ap_CS_fsm.read()) || (esl_seteq<1,5,5>(ap_ST_st13_fsm_12, ap_CS_fsm.read()) && 
  !esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || (esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read()) && 
  !esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || (esl_seteq<1,5,5>(ap_ST_st18_fsm_17, ap_CS_fsm.read()) && 
  !esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()))) {
        localEmpty_fu_100 = empty_assign_fu_88.read();
    }
    if ((esl_seteq<1,5,5>(ap_ST_st7_fsm_6, ap_CS_fsm.read()) && esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0))) {
        localEmpty_load_2_reg_480 = localEmpty_fu_100.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st10_fsm_9, ap_CS_fsm.read())) {
        localEmpty_load_reg_496 = localEmpty_fu_100.read();
    }
    if (((esl_seteq<1,5,5>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, j_phi_fu_172_p4.read())) || esl_seteq<1,5,5>(ap_ST_st5_fsm_4, ap_CS_fsm.read()) || (esl_seteq<1,5,5>(ap_ST_st7_fsm_6, ap_CS_fsm.read()) && 
  esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || (esl_seteq<1,5,5>(ap_ST_st10_fsm_9, ap_CS_fsm.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || (esl_seteq<1,5,5>(ap_ST_st12_fsm_11, ap_CS_fsm.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || esl_seteq<1,5,5>(ap_ST_st17_fsm_16, ap_CS_fsm.read()))) {
        localFull_fu_96 = full_assign_fu_92.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read())) {
        localFull_load_1_reg_526 = localFull_fu_96.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st8_fsm_7, ap_CS_fsm.read())) {
        localFull_load_3_reg_484 = localFull_fu_96.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st13_fsm_12, ap_CS_fsm.read())) {
        localFull_load_4_reg_514 = localFull_fu_96.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st3_fsm_2, ap_CS_fsm.read())) {
        localFull_load_reg_463 = localFull_fu_96.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st12_fsm_11, ap_CS_fsm.read())) {
        result_1_s_reg_500 = result_1_s_fu_353_p2.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st16_fsm_15, ap_CS_fsm.read())) {
        result_load_2_reg_530 = result_fu_80.read();
    }
}

void runQueue::thread_ap_done() {
    if ((esl_seteq<1,5,5>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, j_phi_fu_172_p4.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void runQueue::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,5,5>(ap_ST_st1_fsm_0, ap_CS_fsm.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void runQueue::thread_ap_ready() {
    if ((esl_seteq<1,5,5>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, j_phi_fu_172_p4.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void runQueue::thread_ap_return() {
    ap_return = result_fu_80.read();
}

void runQueue::thread_cmdOut_V() {
    if (((esl_seteq<1,5,5>(ap_ST_st9_fsm_8, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
          esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
          esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
          esl_seteq<1,5,5>(ap_ST_st12_fsm_11, ap_CS_fsm.read())) || 
         (esl_seteq<1,5,5>(ap_ST_st20_fsm_19, ap_CS_fsm.read()) && 
          ((esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
            esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_2_reg_480.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_4_reg_514.read())) || 
           (esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
            esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
            !esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_2_reg_480.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_3_reg_484.read())) || 
           (esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
            !esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
            esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_4_reg_514.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_reg_496.read())) || 
           (esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
            !esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
            !esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_reg_496.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_1_reg_526.read())))) || 
         (esl_seteq<1,5,5>(ap_ST_st7_fsm_6, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
          esl_seteq<1,5,5>(ap_ST_st10_fsm_9, ap_CS_fsm.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
          esl_seteq<1,5,5>(ap_ST_st23_fsm_22, ap_CS_fsm.read())))) {
        cmdOut_V = ap_const_lv2_2;
    } else if (((esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || 
                (!esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) && 
                 esl_seteq<1,5,5>(ap_ST_st23_fsm_22, ap_CS_fsm.read())) || 
                (esl_seteq<1,5,5>(ap_ST_st3_fsm_2, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || 
                (esl_seteq<1,5,5>(ap_ST_st6_fsm_5, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || 
                (esl_seteq<1,5,5>(ap_ST_st8_fsm_7, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || 
                (esl_seteq<1,5,5>(ap_ST_st13_fsm_12, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || 
                (esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || 
                (esl_seteq<1,5,5>(ap_ST_st18_fsm_17, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || 
                (esl_seteq<1,5,5>(ap_ST_st7_fsm_6, ap_CS_fsm.read()) && 
                 esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || 
                (esl_seteq<1,5,5>(ap_ST_st10_fsm_9, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || 
                (esl_seteq<1,5,5>(ap_ST_st12_fsm_11, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || 
                (esl_seteq<1,5,5>(ap_ST_st9_fsm_8, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || 
                (esl_seteq<1,5,5>(ap_ST_st20_fsm_19, ap_CS_fsm.read()) && 
                 ((esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
                   esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_2_reg_480.read()) && 
                   esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_4_reg_514.read()) && 
                   !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || 
                  (esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
                   !esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_2_reg_480.read()) && 
                   esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_3_reg_484.read()) && 
                   !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || 
                  (!esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
                   esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_4_reg_514.read()) && 
                   esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_reg_496.read()) && 
                   !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) || 
                  (!esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
                   !esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_reg_496.read()) && 
                   esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_1_reg_526.read()) && 
                   !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())))) || 
                (esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())))) {
        cmdOut_V = ap_const_lv2_0;
    } else if (((esl_seteq<1,5,5>(ap_ST_st6_fsm_5, ap_CS_fsm.read()) && 
                 esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || 
                esl_seteq<1,5,5>(ap_ST_st19_fsm_18, ap_CS_fsm.read()) || 
                (esl_seteq<1,5,5>(ap_ST_st3_fsm_2, ap_CS_fsm.read()) && 
                 esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) || 
                (esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0) && 
                 esl_seteq<1,5,5>(ap_ST_st13_fsm_12, ap_CS_fsm.read())) || 
                (esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0) && 
                 esl_seteq<1,5,5>(ap_ST_st8_fsm_7, ap_CS_fsm.read())) || 
                (esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0) && 
                 esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read())))) {
        cmdOut_V = ap_const_lv2_1;
    } else {
        cmdOut_V = cmdOut_V_preg.read();
    }
}

void runQueue::thread_currentPriority_V() {
    if (esl_seteq<1,5,5>(ap_ST_st18_fsm_17, ap_CS_fsm.read())) {
        currentPriority_V = tmp_6_reg2mem_reg_238.read();
    } else if ((esl_seteq<1,5,5>(ap_ST_st12_fsm_11, ap_CS_fsm.read()) || 
                esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read()))) {
        currentPriority_V = priorityIn_V.read();
    } else if (esl_seteq<1,5,5>(ap_ST_st6_fsm_5, ap_CS_fsm.read())) {
        currentPriority_V = tmp_reg2mem_reg_191.read();
    } else {
        currentPriority_V = currentPriority_V_preg.read();
    }
}

void runQueue::thread_empty_read_read_fu_110_p2() {
    empty_read_read_fu_110_p2 =  (sc_lv<1>) (empty.read());
}

void runQueue::thread_fullOut() {
    if (esl_seteq<1,5,5>(ap_ST_st4_fsm_3, ap_CS_fsm.read())) {
        fullOut =  (sc_logic) (full_assign_fu_92.read()[0]);
    } else {
        fullOut = fullOut_preg.read();
    }
}

void runQueue::thread_full_read_read_fu_104_p2() {
    full_read_read_fu_104_p2 =  (sc_lv<1>) (full.read());
}

void runQueue::thread_grp_fu_291_p2() {
    grp_fu_291_p2 = (!last_1_reg_446.read().is_01() || !last_load_reg_458.read().is_01())? sc_lv<1>(): (sc_biguint<32>(last_1_reg_446.read()) < sc_biguint<32>(last_load_reg_458.read()));
}

void runQueue::thread_grp_fu_295_p2() {
    grp_fu_295_p2 = (grp_fu_291_p2.read() ^ ap_const_lv1_1);
}

void runQueue::thread_grp_fu_301_p2() {
    grp_fu_301_p2 = (grp_fu_295_p2.read() & result_load_reg_453.read());
}

void runQueue::thread_grp_load_fu_277_p1() {
    grp_load_fu_277_p1 = localFull_fu_96.read();
}

void runQueue::thread_grp_load_fu_288_p1() {
    grp_load_fu_288_p1 = localEmpty_fu_100.read();
}

void runQueue::thread_i8_fu_337_p2() {
    i8_fu_337_p2 = (!i_reg2mem_reg_180.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(i_reg2mem_reg_180.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void runQueue::thread_i_1_fu_371_p2() {
    i_1_fu_371_p2 = (!i_3_reg2mem_reg_227.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(i_3_reg2mem_reg_227.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void runQueue::thread_i_s_fu_360_p2() {
    i_s_fu_360_p2 = (!i_1_reg2mem_reg_214.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(i_1_reg2mem_reg_214.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void runQueue::thread_j_phi_fu_172_p4() {
    j_phi_fu_172_p4 = j_reg_167.read();
}

void runQueue::thread_last_1_fu_320_p1() {
    last_1_fu_320_p1 = esl_zext<32,4>(priorityIn_V.read());
}

void runQueue::thread_p_result_2_fu_366_p2() {
    p_result_2_fu_366_p2 = (grp_fu_295_p2.read() & result_1_s_reg_500.read());
}

void runQueue::thread_p_result_3_fu_387_p2() {
    p_result_3_fu_387_p2 = (grp_fu_295_p2.read() & result_load_2_reg_530.read());
}

void runQueue::thread_priorityOut_V() {
    if (esl_seteq<1,5,5>(ap_ST_st19_fsm_18, ap_CS_fsm.read())) {
        priorityOut_V = tmp_1_fu_382_p1.read();
    } else if (((esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0) && 
                 esl_seteq<1,5,5>(ap_ST_st13_fsm_12, ap_CS_fsm.read())) || 
                (esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0) && 
                 esl_seteq<1,5,5>(ap_ST_st8_fsm_7, ap_CS_fsm.read())) || 
                (esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0) && 
                 esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read())))) {
        priorityOut_V = ap_const_lv4_5;
    } else if ((esl_seteq<1,5,5>(ap_ST_st6_fsm_5, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0))) {
        priorityOut_V = tmp_fu_343_p1.read();
    } else if ((esl_seteq<1,5,5>(ap_ST_st3_fsm_2, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0))) {
        priorityOut_V = ap_const_lv4_0;
    } else {
        priorityOut_V = priorityOut_V_preg.read();
    }
}

void runQueue::thread_random_priorities_address0() {
    random_priorities_address0 =  (sc_lv<8>) (tmp_s_fu_377_p1.read());
}

void runQueue::thread_random_priorities_ce0() {
    if (esl_seteq<1,5,5>(ap_ST_st18_fsm_17, ap_CS_fsm.read())) {
        random_priorities_ce0 = ap_const_logic_1;
    } else {
        random_priorities_ce0 = ap_const_logic_0;
    }
}

void runQueue::thread_result_1_s_fu_353_p2() {
    result_1_s_fu_353_p2 = (tmp_3_fu_348_p2.read() & result_fu_80.read());
}

void runQueue::thread_tmp_1_fu_382_p1() {
    tmp_1_fu_382_p1 = random_priorities_q0.read().range(4-1, 0);
}

void runQueue::thread_tmp_3_fu_348_p2() {
    tmp_3_fu_348_p2 = (!last_1_reg_446.read().is_01() || !op2_assign_reg2mem_reg_203.read().is_01())? sc_lv<1>(): sc_lv<1>(last_1_reg_446.read() == op2_assign_reg2mem_reg_203.read());
}

void runQueue::thread_tmp_fu_343_p1() {
    tmp_fu_343_p1 = i_reg2mem_reg_180.read().range(4-1, 0);
}

void runQueue::thread_tmp_s_fu_377_p1() {
    tmp_s_fu_377_p1 = esl_sext<64,32>(i_3_reg2mem_reg_227.read());
}

void runQueue::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint()) {
        case 0 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, j_phi_fu_172_p4.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st10_fsm_9;
            }
            break;
        case 3 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 5 : 
            if (esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            }
            break;
        case 6 : 
            if ((esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) || !esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_st11_fsm_10;
            } else {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            }
            break;
        case 7 : 
            if (esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st16_fsm_15;
            } else {
                ap_NS_fsm = ap_ST_st9_fsm_8;
            }
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) {
                ap_NS_fsm = ap_ST_st24_fsm_23;
            } else {
                ap_NS_fsm = ap_ST_st20_fsm_19;
            }
            break;
        case 9 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            } else {
                ap_NS_fsm = ap_ST_st15_fsm_14;
            }
            break;
        case 10 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 11 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) {
                ap_NS_fsm = ap_ST_st11_fsm_10;
            } else {
                ap_NS_fsm = ap_ST_st13_fsm_12;
            }
            break;
        case 12 : 
            if (esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st16_fsm_15;
            } else {
                ap_NS_fsm = ap_ST_st14_fsm_13;
            }
            break;
        case 13 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) {
                ap_NS_fsm = ap_ST_st24_fsm_23;
            } else {
                ap_NS_fsm = ap_ST_st20_fsm_19;
            }
            break;
        case 14 : 
            if (esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st16_fsm_15;
            } else {
                ap_NS_fsm = ap_ST_st21_fsm_20;
            }
            break;
        case 15 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
            break;
        case 17 : 
            if (!esl_seteq<1,1,1>(grp_load_fu_277_p1.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st20_fsm_19;
            } else {
                ap_NS_fsm = ap_ST_st19_fsm_18;
            }
            break;
        case 18 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 19 : 
            if ((esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read()) || (esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_2_reg_480.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_4_reg_514.read())) || (esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_2_reg_480.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_3_reg_484.read())) || (!esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_reg_496.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_4_reg_514.read())) || (!esl_seteq<1,1,1>(localFull_load_reg_463.read(), ap_const_lv1_0) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, localEmpty_load_reg_496.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, localFull_load_1_reg_526.read())))) {
                ap_NS_fsm = ap_ST_st22_fsm_21;
            } else {
                ap_NS_fsm = ap_ST_st24_fsm_23;
            }
            break;
        case 20 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) {
                ap_NS_fsm = ap_ST_st24_fsm_23;
            } else {
                ap_NS_fsm = ap_ST_st20_fsm_19;
            }
            break;
        case 21 : 
            ap_NS_fsm = ap_ST_st23_fsm_22;
            break;
        case 22 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, grp_load_fu_288_p1.read())) {
                ap_NS_fsm = ap_ST_st24_fsm_23;
            } else {
                ap_NS_fsm = ap_ST_st22_fsm_21;
            }
            break;
        case 23 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        default : 
            ap_NS_fsm = "XXXXX";
            break;
    }
}
void runQueue::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"priorityOut_V\" :  \"" << priorityOut_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"priorityIn_V\" :  \"" << priorityIn_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"cmdOut_V\" :  \"" << cmdOut_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"empty\" :  \"" << empty.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"full\" :  \"" << full.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"currentPriority_V\" :  \"" << currentPriority_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"fullOut\" :  \"" << fullOut.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

