// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module runTest (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_return
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 4'b0000;
parameter    ap_ST_st2_fsm_1 = 4'b1;
parameter    ap_ST_st3_fsm_2 = 4'b10;
parameter    ap_ST_st4_fsm_3 = 4'b11;
parameter    ap_ST_st5_fsm_4 = 4'b100;
parameter    ap_ST_st6_fsm_5 = 4'b101;
parameter    ap_ST_st7_fsm_6 = 4'b110;
parameter    ap_ST_st8_fsm_7 = 4'b111;
parameter    ap_ST_st9_fsm_8 = 4'b1000;
parameter    ap_ST_st10_fsm_9 = 4'b1001;
parameter    ap_ST_st11_fsm_10 = 4'b1010;
parameter    ap_ST_st12_fsm_11 = 4'b1011;
parameter    ap_ST_st13_fsm_12 = 4'b1100;
parameter    ap_ST_st14_fsm_13 = 4'b1101;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv32_FFFFFFFF = 32'b11111111111111111111111111111111;
parameter    ap_const_lv8_C8 = 8'b11001000;
parameter    ap_const_lv8_1 = 8'b1;
parameter    ap_const_lv8_C7 = 8'b11000111;
parameter    ap_const_lv32_C8 = 32'b11001000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [0:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[0:0] ap_return;
reg   [3:0] ap_CS_fsm = 4'b0000;
wire   [7:0] random_priorities_address0;
reg    random_priorities_ce0;
wire   [8:0] random_priorities_q0;
wire   [7:0] i_fu_210_p2;
reg   [7:0] i_reg_376;
wire   [7:0] current_data_fu_216_p2;
reg   [7:0] current_data_reg_381;
wire   [0:0] exitcond4_fu_204_p2;
wire   [8:0] current_priority_cast6_cast_fu_223_p1;
reg   [8:0] current_priority_cast6_cast_reg_386;
wire   [31:0] i_1_cast5_fu_228_p1;
reg   [31:0] i_1_cast5_reg_391;
wire   [7:0] i_6_fu_238_p2;
reg   [7:0] i_6_reg_399;
wire   [0:0] tmp_2_fu_265_p2;
reg   [0:0] tmp_2_reg_404;
wire    grp_queue_fu_174_ap_done;
wire   [0:0] result_s_fu_271_p2;
wire   [7:0] i_5_fu_282_p2;
reg   [7:0] i_5_reg_417;
wire   [0:0] exitcond2_fu_276_p2;
wire   [7:0] current_data_1_fu_293_p2;
reg   [7:0] current_data_1_reg_427;
reg   [8:0] current_priority_1_reg_432;
wire   [7:0] i_7_fu_306_p2;
wire   [7:0] i_8_fu_323_p2;
reg   [7:0] i_8_reg_448;
reg   [31:0] out_priority_2_reg_453;
reg   [31:0] out_data_1_reg_458;
wire   [0:0] slt_fu_329_p2;
reg   [0:0] slt_reg_464;
reg   [7:0] dequeuedItems_addr_1_reg_469;
wire   [0:0] tmp_7_fu_362_p2;
reg   [0:0] tmp_7_reg_474;
wire   [0:0] result_4_fu_368_p2;
reg   [7:0] dequeuedItems_address0;
reg    dequeuedItems_ce0;
reg    dequeuedItems_we0;
reg   [31:0] dequeuedItems_d0;
wire   [31:0] dequeuedItems_q0;
wire    grp_queue_fu_174_ap_start;
wire    grp_queue_fu_174_ap_idle;
wire    grp_queue_fu_174_ap_ready;
reg    grp_queue_fu_174_isPush;
reg   [8:0] grp_queue_fu_174_inData_priority;
reg   [7:0] grp_queue_fu_174_inData_data;
wire   [31:0] grp_queue_fu_174_ap_return_0;
wire   [31:0] grp_queue_fu_174_ap_return_1;
reg   [7:0] current_priority_reg_81;
reg   [0:0] result_reg_92;
reg   [7:0] i_1_reg_104;
reg   [7:0] i_2_reg_116;
wire   [0:0] exitcond3_fu_232_p2;
reg   [7:0] i_3_reg_128;
wire   [0:0] exitcond1_fu_300_p2;
reg   [31:0] last_reg_139;
reg   [0:0] result_2_reg_151;
reg   [7:0] i_4_reg_162;
reg    grp_queue_fu_174_ap_start_ap_start_reg = 1'b0;
wire   [0:0] exitcond_fu_317_p2;
wire   [63:0] tmp_6_fu_288_p1;
wire   [63:0] tmp_9_fu_312_p1;
wire   [63:0] tmp_1_fu_335_p1;
wire   [7:0] tmp_3_fu_249_p2;
wire   [31:0] tmp_3_cast_fu_255_p1;
wire   [0:0] tmp_4_fu_259_p2;
wire   [0:0] tmp_fu_244_p2;
wire   [0:0] notlhs_fu_345_p2;
wire   [0:0] notrhs_fu_350_p2;
wire   [0:0] tmp2_fu_356_p2;
wire   [0:0] rev1_fu_340_p2;
reg   [0:0] ap_return_preg = 1'b0;
reg   [3:0] ap_NS_fsm;


runTest_random_priorities #(
    .DataWidth( 9 ),
    .AddressRange( 200 ),
    .AddressWidth( 8 ))
random_priorities_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( random_priorities_address0 ),
    .ce0( random_priorities_ce0 ),
    .q0( random_priorities_q0 )
);

runTest_dequeuedItems #(
    .DataWidth( 32 ),
    .AddressRange( 200 ),
    .AddressWidth( 8 ))
dequeuedItems_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( dequeuedItems_address0 ),
    .ce0( dequeuedItems_ce0 ),
    .we0( dequeuedItems_we0 ),
    .d0( dequeuedItems_d0 ),
    .q0( dequeuedItems_q0 )
);

queue grp_queue_fu_174(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_queue_fu_174_ap_start ),
    .ap_done( grp_queue_fu_174_ap_done ),
    .ap_idle( grp_queue_fu_174_ap_idle ),
    .ap_ready( grp_queue_fu_174_ap_ready ),
    .isPush( grp_queue_fu_174_isPush ),
    .inData_priority( grp_queue_fu_174_inData_priority ),
    .inData_data( grp_queue_fu_174_inData_data ),
    .ap_return_0( grp_queue_fu_174_ap_return_0 ),
    .ap_return_1( grp_queue_fu_174_ap_return_1 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_return_preg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_return_preg
    if (ap_rst == 1'b1) begin
        ap_return_preg <= ap_const_lv1_0;
    end else begin
        if (((ap_ST_st11_fsm_10 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_317_p2))) begin
            ap_return_preg <= result_2_reg_151;
        end
    end
end

/// grp_queue_fu_174_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_queue_fu_174_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_queue_fu_174_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if ((((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond4_fu_204_p2 == ap_const_lv1_0)) | (ap_ST_st8_fsm_7 == ap_CS_fsm) | ((ap_ST_st4_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_232_p2)) | ((ap_ST_st11_fsm_10 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_fu_317_p2)))) begin
            grp_queue_fu_174_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_queue_fu_174_ap_ready)) begin
            grp_queue_fu_174_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_logic_0 == grp_queue_fu_174_ap_done) & (ap_ST_st3_fsm_2 == ap_CS_fsm))) begin
        current_priority_reg_81 <= i_reg_376;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0))) begin
        current_priority_reg_81 <= ap_const_lv8_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(exitcond4_fu_204_p2 == ap_const_lv1_0))) begin
        i_1_reg_104 <= ap_const_lv8_0;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        i_1_reg_104 <= i_6_reg_399;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond3_fu_232_p2))) begin
        i_2_reg_116 <= ap_const_lv8_0;
    end else if ((~(ap_const_logic_0 == grp_queue_fu_174_ap_done) & (ap_ST_st9_fsm_8 == ap_CS_fsm))) begin
        i_2_reg_116 <= i_5_reg_417;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond2_fu_276_p2))) begin
        i_3_reg_128 <= ap_const_lv8_0;
    end else if (((ap_ST_st10_fsm_9 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_300_p2))) begin
        i_3_reg_128 <= i_7_fu_306_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st10_fsm_9 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond1_fu_300_p2))) begin
        i_4_reg_162 <= ap_const_lv8_0;
    end else if ((ap_ST_st14_fsm_13 == ap_CS_fsm)) begin
        i_4_reg_162 <= i_8_reg_448;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st10_fsm_9 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond1_fu_300_p2))) begin
        last_reg_139 <= ap_const_lv32_0;
    end else if ((ap_ST_st14_fsm_13 == ap_CS_fsm)) begin
        last_reg_139 <= out_priority_2_reg_453;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st10_fsm_9 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond1_fu_300_p2))) begin
        result_2_reg_151 <= result_reg_92;
    end else if ((ap_ST_st14_fsm_13 == ap_CS_fsm)) begin
        result_2_reg_151 <= result_4_fu_368_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(exitcond4_fu_204_p2 == ap_const_lv1_0))) begin
        result_reg_92 <= ap_const_lv1_1;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        result_reg_92 <= result_s_fu_271_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st8_fsm_7 == ap_CS_fsm)) begin
        current_data_1_reg_427 <= current_data_1_fu_293_p2;
        current_priority_1_reg_432 <= random_priorities_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond4_fu_204_p2 == ap_const_lv1_0))) begin
        current_data_reg_381 <= current_data_fu_216_p2;
        current_priority_cast6_cast_reg_386[0] <= current_priority_cast6_cast_fu_223_p1[0];
current_priority_cast6_cast_reg_386[1] <= current_priority_cast6_cast_fu_223_p1[1];
current_priority_cast6_cast_reg_386[2] <= current_priority_cast6_cast_fu_223_p1[2];
current_priority_cast6_cast_reg_386[3] <= current_priority_cast6_cast_fu_223_p1[3];
current_priority_cast6_cast_reg_386[4] <= current_priority_cast6_cast_fu_223_p1[4];
current_priority_cast6_cast_reg_386[5] <= current_priority_cast6_cast_fu_223_p1[5];
current_priority_cast6_cast_reg_386[6] <= current_priority_cast6_cast_fu_223_p1[6];
current_priority_cast6_cast_reg_386[7] <= current_priority_cast6_cast_fu_223_p1[7];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_logic_0 == grp_queue_fu_174_ap_done) & (ap_ST_st12_fsm_11 == ap_CS_fsm))) begin
        dequeuedItems_addr_1_reg_469 <= tmp_1_fu_335_p1;
        out_data_1_reg_458 <= grp_queue_fu_174_ap_return_1;
        out_priority_2_reg_453 <= grp_queue_fu_174_ap_return_0;
        slt_reg_464 <= slt_fu_329_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        i_1_cast5_reg_391[0] <= i_1_cast5_fu_228_p1[0];
i_1_cast5_reg_391[1] <= i_1_cast5_fu_228_p1[1];
i_1_cast5_reg_391[2] <= i_1_cast5_fu_228_p1[2];
i_1_cast5_reg_391[3] <= i_1_cast5_fu_228_p1[3];
i_1_cast5_reg_391[4] <= i_1_cast5_fu_228_p1[4];
i_1_cast5_reg_391[5] <= i_1_cast5_fu_228_p1[5];
i_1_cast5_reg_391[6] <= i_1_cast5_fu_228_p1[6];
i_1_cast5_reg_391[7] <= i_1_cast5_fu_228_p1[7];
        i_6_reg_399 <= i_6_fu_238_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st7_fsm_6 == ap_CS_fsm)) begin
        i_5_reg_417 <= i_5_fu_282_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st11_fsm_10 == ap_CS_fsm)) begin
        i_8_reg_448 <= i_8_fu_323_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        i_reg_376 <= i_fu_210_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_queue_fu_174_ap_done))) begin
        tmp_2_reg_404 <= tmp_2_fu_265_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st13_fsm_12 == ap_CS_fsm)) begin
        tmp_7_reg_474 <= tmp_7_fu_362_p2;
    end
end

/// ap_done assign process. ///
always @ (ap_start or ap_CS_fsm or exitcond_fu_317_p2)
begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm)) | ((ap_ST_st11_fsm_10 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_317_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or exitcond_fu_317_p2)
begin
    if (((ap_ST_st11_fsm_10 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_317_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_return assign process. ///
always @ (ap_CS_fsm or result_2_reg_151 or exitcond_fu_317_p2 or ap_return_preg)
begin
    if (((ap_ST_st11_fsm_10 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_317_p2))) begin
        ap_return = result_2_reg_151;
    end else begin
        ap_return = ap_return_preg;
    end
end

/// dequeuedItems_address0 assign process. ///
always @ (ap_CS_fsm or dequeuedItems_addr_1_reg_469 or tmp_9_fu_312_p1 or tmp_1_fu_335_p1)
begin
    if ((ap_ST_st13_fsm_12 == ap_CS_fsm)) begin
        dequeuedItems_address0 = dequeuedItems_addr_1_reg_469;
    end else if ((ap_ST_st10_fsm_9 == ap_CS_fsm)) begin
        dequeuedItems_address0 = tmp_9_fu_312_p1;
    end else if ((ap_ST_st12_fsm_11 == ap_CS_fsm)) begin
        dequeuedItems_address0 = tmp_1_fu_335_p1;
    end else begin
        dequeuedItems_address0 = 'bx;
    end
end

/// dequeuedItems_ce0 assign process. ///
always @ (ap_CS_fsm or grp_queue_fu_174_ap_done)
begin
    if (((ap_ST_st10_fsm_9 == ap_CS_fsm) | (~(ap_const_logic_0 == grp_queue_fu_174_ap_done) & (ap_ST_st12_fsm_11 == ap_CS_fsm)) | (ap_ST_st13_fsm_12 == ap_CS_fsm))) begin
        dequeuedItems_ce0 = ap_const_logic_1;
    end else begin
        dequeuedItems_ce0 = ap_const_logic_0;
    end
end

/// dequeuedItems_d0 assign process. ///
always @ (ap_CS_fsm or out_data_1_reg_458)
begin
    if ((ap_ST_st13_fsm_12 == ap_CS_fsm)) begin
        dequeuedItems_d0 = out_data_1_reg_458;
    end else if ((ap_ST_st10_fsm_9 == ap_CS_fsm)) begin
        dequeuedItems_d0 = ap_const_lv32_FFFFFFFF;
    end else begin
        dequeuedItems_d0 = 'bx;
    end
end

/// dequeuedItems_we0 assign process. ///
always @ (ap_CS_fsm or exitcond1_fu_300_p2)
begin
    if (((ap_ST_st13_fsm_12 == ap_CS_fsm) | ((ap_ST_st10_fsm_9 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_300_p2)))) begin
        dequeuedItems_we0 = ap_const_logic_1;
    end else begin
        dequeuedItems_we0 = ap_const_logic_0;
    end
end

/// grp_queue_fu_174_inData_data assign process. ///
always @ (ap_CS_fsm or current_data_reg_381 or current_data_1_reg_427)
begin
    if ((ap_ST_st9_fsm_8 == ap_CS_fsm)) begin
        grp_queue_fu_174_inData_data = current_data_1_reg_427;
    end else if (((ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st12_fsm_11 == ap_CS_fsm))) begin
        grp_queue_fu_174_inData_data = ap_const_lv8_0;
    end else if ((ap_ST_st3_fsm_2 == ap_CS_fsm)) begin
        grp_queue_fu_174_inData_data = current_data_reg_381;
    end else begin
        grp_queue_fu_174_inData_data = 'bx;
    end
end

/// grp_queue_fu_174_inData_priority assign process. ///
always @ (ap_CS_fsm or current_priority_cast6_cast_reg_386 or current_priority_1_reg_432)
begin
    if ((ap_ST_st9_fsm_8 == ap_CS_fsm)) begin
        grp_queue_fu_174_inData_priority = current_priority_1_reg_432;
    end else if (((ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st12_fsm_11 == ap_CS_fsm))) begin
        grp_queue_fu_174_inData_priority = ap_const_lv9_0;
    end else if ((ap_ST_st3_fsm_2 == ap_CS_fsm)) begin
        grp_queue_fu_174_inData_priority = current_priority_cast6_cast_reg_386;
    end else begin
        grp_queue_fu_174_inData_priority = 'bx;
    end
end

/// grp_queue_fu_174_isPush assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st12_fsm_11 == ap_CS_fsm))) begin
        grp_queue_fu_174_isPush = ap_const_lv1_0;
    end else if (((ap_ST_st3_fsm_2 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm))) begin
        grp_queue_fu_174_isPush = ap_const_lv1_1;
    end else begin
        grp_queue_fu_174_isPush = 'bx;
    end
end

/// random_priorities_ce0 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st7_fsm_6 == ap_CS_fsm)) begin
        random_priorities_ce0 = ap_const_logic_1;
    end else begin
        random_priorities_ce0 = ap_const_logic_0;
    end
end
always @ (ap_start or ap_CS_fsm or exitcond4_fu_204_p2 or grp_queue_fu_174_ap_done or exitcond2_fu_276_p2 or exitcond3_fu_232_p2 or exitcond1_fu_300_p2 or exitcond_fu_317_p2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            if (~(exitcond4_fu_204_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        ap_ST_st3_fsm_2 : 
            if (~(ap_const_logic_0 == grp_queue_fu_174_ap_done)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        ap_ST_st4_fsm_3 : 
            if (~(ap_const_lv1_0 == exitcond3_fu_232_p2)) begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        ap_ST_st5_fsm_4 : 
            if (~(ap_const_logic_0 == grp_queue_fu_174_ap_done)) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        ap_ST_st6_fsm_5 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
        ap_ST_st7_fsm_6 : 
            if (~(ap_const_lv1_0 == exitcond2_fu_276_p2)) begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end else begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end
        ap_ST_st8_fsm_7 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
        ap_ST_st9_fsm_8 : 
            if (~(ap_const_logic_0 == grp_queue_fu_174_ap_done)) begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end
        ap_ST_st10_fsm_9 : 
            if ((ap_const_lv1_0 == exitcond1_fu_300_p2)) begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end else begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end
        ap_ST_st11_fsm_10 : 
            if (~(ap_const_lv1_0 == exitcond_fu_317_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st12_fsm_11;
            end
        ap_ST_st12_fsm_11 : 
            if (~(ap_const_logic_0 == grp_queue_fu_174_ap_done)) begin
                ap_NS_fsm = ap_ST_st13_fsm_12;
            end else begin
                ap_NS_fsm = ap_ST_st12_fsm_11;
            end
        ap_ST_st13_fsm_12 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
        ap_ST_st14_fsm_13 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
        default : 
            ap_NS_fsm = 'bx;
    endcase
end
assign current_data_1_fu_293_p2 = (ap_const_lv8_C7 - i_2_reg_116);
assign current_data_fu_216_p2 = (ap_const_lv8_C7 - current_priority_reg_81);
assign current_priority_cast6_cast_fu_223_p1 = $unsigned(current_priority_reg_81);
assign exitcond1_fu_300_p2 = (i_3_reg_128 == ap_const_lv8_C8? 1'b1: 1'b0);
assign exitcond2_fu_276_p2 = (i_2_reg_116 == ap_const_lv8_C8? 1'b1: 1'b0);
assign exitcond3_fu_232_p2 = (i_1_reg_104 == ap_const_lv8_C8? 1'b1: 1'b0);
assign exitcond4_fu_204_p2 = (current_priority_reg_81 == ap_const_lv8_C8? 1'b1: 1'b0);
assign exitcond_fu_317_p2 = (i_4_reg_162 == ap_const_lv8_C8? 1'b1: 1'b0);
assign grp_queue_fu_174_ap_start = grp_queue_fu_174_ap_start_ap_start_reg;
assign i_1_cast5_fu_228_p1 = $unsigned(i_1_reg_104);
assign i_5_fu_282_p2 = (i_2_reg_116 + ap_const_lv8_1);
assign i_6_fu_238_p2 = (i_1_reg_104 + ap_const_lv8_1);
assign i_7_fu_306_p2 = (i_3_reg_128 + ap_const_lv8_1);
assign i_8_fu_323_p2 = (i_4_reg_162 + ap_const_lv8_1);
assign i_fu_210_p2 = (current_priority_reg_81 + ap_const_lv8_1);
assign notlhs_fu_345_p2 = ($signed(out_data_1_reg_458) < $signed(32'b11001000)? 1'b1: 1'b0);
assign notrhs_fu_350_p2 = ($signed(dequeuedItems_q0) < $signed(32'b1)? 1'b1: 1'b0);
assign random_priorities_address0 = tmp_6_fu_288_p1;
assign result_4_fu_368_p2 = (result_2_reg_151 & tmp_7_reg_474);
assign result_s_fu_271_p2 = (result_reg_92 & tmp_2_reg_404);
assign rev1_fu_340_p2 = (slt_reg_464 ^ ap_const_lv1_1);
assign slt_fu_329_p2 = ($signed(grp_queue_fu_174_ap_return_0) < $signed(last_reg_139)? 1'b1: 1'b0);
assign tmp2_fu_356_p2 = (notlhs_fu_345_p2 & notrhs_fu_350_p2);
assign tmp_1_fu_335_p1 = $signed(grp_queue_fu_174_ap_return_1);
assign tmp_2_fu_265_p2 = (tmp_4_fu_259_p2 & tmp_fu_244_p2);
assign tmp_3_cast_fu_255_p1 = $unsigned(tmp_3_fu_249_p2);
assign tmp_3_fu_249_p2 = (ap_const_lv8_C7 - i_1_reg_104);
assign tmp_4_fu_259_p2 = (grp_queue_fu_174_ap_return_1 == tmp_3_cast_fu_255_p1? 1'b1: 1'b0);
assign tmp_6_fu_288_p1 = $unsigned(i_2_reg_116);
assign tmp_7_fu_362_p2 = (tmp2_fu_356_p2 & rev1_fu_340_p2);
assign tmp_9_fu_312_p1 = $unsigned(i_3_reg_128);
assign tmp_fu_244_p2 = (grp_queue_fu_174_ap_return_0 == i_1_cast5_reg_391? 1'b1: 1'b0);
always @ (posedge ap_clk)
begin
    current_priority_cast6_cast_reg_386[8] <= 1'b0;
    i_1_cast5_reg_391[31:8] <= 24'b000000000000000000000000;
end



endmodule //runTest

