webtalk_init -webtalk_dir /home/michael/ecen5139_final_project/CAV_Vivado_NoHdmi/CAV_Vivado_NoHdmi.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 8 03:31:24 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "sae87t98h2mperlg4jcp8a0q1d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.2_7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394.451 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1449570677000" -context "sdk\\\\hardware/1449570677000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1449570677000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1449570677000"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.2" -context "sdk\\\\hardware/1449570677000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1449570677000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1449570677000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1449570677000"
webtalk_transmit -clientid 1260511144 -regid "NA" -xml /home/michael/ecen5139_final_project/CAV_Vivado_NoHdmi/CAV_Vivado_NoHdmi.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/michael/ecen5139_final_project/CAV_Vivado_NoHdmi/CAV_Vivado_NoHdmi.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/michael/ecen5139_final_project/CAV_Vivado_NoHdmi/CAV_Vivado_NoHdmi.sdk/webtalk/sdk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
