// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "queue.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic queue::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic queue::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> queue::ap_ST_st1_fsm_0 = "0";
const sc_lv<1> queue::ap_ST_st2_fsm_1 = "1";
const sc_lv<32> queue::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> queue::ap_const_lv1_0 = "0";
const sc_lv<32> queue::ap_const_lv32_7FFFFFFF = "1111111111111111111111111111111";
const sc_lv<32> queue::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<32> queue::ap_const_lv32_C8 = "11001000";

queue::queue(sc_module_name name) : sc_module(name), mVcdFile(0) {
    queueData_priority_U = new queue_queueData_priority("queueData_priority_U");
    queueData_priority_U->clk(ap_clk);
    queueData_priority_U->reset(ap_rst);
    queueData_priority_U->address0(queueData_priority_address0);
    queueData_priority_U->ce0(queueData_priority_ce0);
    queueData_priority_U->we0(queueData_priority_we0);
    queueData_priority_U->d0(queueData_priority_d0);
    queueData_priority_U->q0(queueData_priority_q0);
    queueData_priority_U->address1(queueData_priority_address1);
    queueData_priority_U->ce1(queueData_priority_ce1);
    queueData_priority_U->we1(queueData_priority_we1);
    queueData_priority_U->d1(queueData_priority_d1);
    queueData_priority_U->q1(queueData_priority_q1);
    queueData_data_U = new queue_queueData_priority("queueData_data_U");
    queueData_data_U->clk(ap_clk);
    queueData_data_U->reset(ap_rst);
    queueData_data_U->address0(queueData_data_address0);
    queueData_data_U->ce0(queueData_data_ce0);
    queueData_data_U->we0(queueData_data_we0);
    queueData_data_U->d0(queueData_data_d0);
    queueData_data_U->q0(queueData_data_q0);
    queueData_data_U->address1(queueData_data_address1);
    queueData_data_U->ce1(queueData_data_ce1);
    queueData_data_U->we1(queueData_data_we1);
    queueData_data_U->d1(queueData_data_d1);
    queueData_data_U->q1(queueData_data_q1);
    tempData_priority_U = new queue_queueData_priority("tempData_priority_U");
    tempData_priority_U->clk(ap_clk);
    tempData_priority_U->reset(ap_rst);
    tempData_priority_U->address0(tempData_priority_address0);
    tempData_priority_U->ce0(tempData_priority_ce0);
    tempData_priority_U->we0(tempData_priority_we0);
    tempData_priority_U->d0(tempData_priority_d0);
    tempData_priority_U->q0(tempData_priority_q0);
    tempData_priority_U->address1(tempData_priority_address1);
    tempData_priority_U->ce1(tempData_priority_ce1);
    tempData_priority_U->we1(tempData_priority_we1);
    tempData_priority_U->d1(tempData_priority_d1);
    tempData_priority_U->q1(tempData_priority_q1);
    tempData_data_U = new queue_queueData_priority("tempData_data_U");
    tempData_data_U->clk(ap_clk);
    tempData_data_U->reset(ap_rst);
    tempData_data_U->address0(tempData_data_address0);
    tempData_data_U->ce0(tempData_data_ce0);
    tempData_data_U->we0(tempData_data_we0);
    tempData_data_U->d0(tempData_data_d0);
    tempData_data_U->q0(tempData_data_q0);
    tempData_data_U->address1(tempData_data_address1);
    tempData_data_U->ce1(tempData_data_ce1);
    tempData_data_U->we1(tempData_data_we1);
    tempData_data_U->d1(tempData_data_d1);
    tempData_data_U->q1(tempData_data_q1);
    grp_push_fu_87 = new push("grp_push_fu_87");
    grp_push_fu_87->ap_clk(ap_clk);
    grp_push_fu_87->ap_rst(ap_rst);
    grp_push_fu_87->ap_start(grp_push_fu_87_ap_start);
    grp_push_fu_87->ap_done(grp_push_fu_87_ap_done);
    grp_push_fu_87->ap_idle(grp_push_fu_87_ap_idle);
    grp_push_fu_87->ap_ready(grp_push_fu_87_ap_ready);
    grp_push_fu_87->queueData_priority_address0(grp_push_fu_87_queueData_priority_address0);
    grp_push_fu_87->queueData_priority_ce0(grp_push_fu_87_queueData_priority_ce0);
    grp_push_fu_87->queueData_priority_we0(grp_push_fu_87_queueData_priority_we0);
    grp_push_fu_87->queueData_priority_d0(grp_push_fu_87_queueData_priority_d0);
    grp_push_fu_87->queueData_priority_q0(grp_push_fu_87_queueData_priority_q0);
    grp_push_fu_87->queueData_priority_address1(grp_push_fu_87_queueData_priority_address1);
    grp_push_fu_87->queueData_priority_ce1(grp_push_fu_87_queueData_priority_ce1);
    grp_push_fu_87->queueData_priority_we1(grp_push_fu_87_queueData_priority_we1);
    grp_push_fu_87->queueData_priority_d1(grp_push_fu_87_queueData_priority_d1);
    grp_push_fu_87->queueData_priority_q1(grp_push_fu_87_queueData_priority_q1);
    grp_push_fu_87->queueData_data_address0(grp_push_fu_87_queueData_data_address0);
    grp_push_fu_87->queueData_data_ce0(grp_push_fu_87_queueData_data_ce0);
    grp_push_fu_87->queueData_data_we0(grp_push_fu_87_queueData_data_we0);
    grp_push_fu_87->queueData_data_d0(grp_push_fu_87_queueData_data_d0);
    grp_push_fu_87->queueData_data_q0(grp_push_fu_87_queueData_data_q0);
    grp_push_fu_87->queueData_data_address1(grp_push_fu_87_queueData_data_address1);
    grp_push_fu_87->queueData_data_ce1(grp_push_fu_87_queueData_data_ce1);
    grp_push_fu_87->queueData_data_we1(grp_push_fu_87_queueData_data_we1);
    grp_push_fu_87->queueData_data_d1(grp_push_fu_87_queueData_data_d1);
    grp_push_fu_87->queueData_data_q1(grp_push_fu_87_queueData_data_q1);
    grp_push_fu_87->size(grp_push_fu_87_size);
    grp_push_fu_87->item_priority(grp_push_fu_87_item_priority);
    grp_push_fu_87->item_data(grp_push_fu_87_item_data);
    grp_push_fu_87->tempData_priority_address0(grp_push_fu_87_tempData_priority_address0);
    grp_push_fu_87->tempData_priority_ce0(grp_push_fu_87_tempData_priority_ce0);
    grp_push_fu_87->tempData_priority_we0(grp_push_fu_87_tempData_priority_we0);
    grp_push_fu_87->tempData_priority_d0(grp_push_fu_87_tempData_priority_d0);
    grp_push_fu_87->tempData_priority_q0(grp_push_fu_87_tempData_priority_q0);
    grp_push_fu_87->tempData_priority_address1(grp_push_fu_87_tempData_priority_address1);
    grp_push_fu_87->tempData_priority_ce1(grp_push_fu_87_tempData_priority_ce1);
    grp_push_fu_87->tempData_priority_we1(grp_push_fu_87_tempData_priority_we1);
    grp_push_fu_87->tempData_priority_d1(grp_push_fu_87_tempData_priority_d1);
    grp_push_fu_87->tempData_priority_q1(grp_push_fu_87_tempData_priority_q1);
    grp_push_fu_87->tempData_data_address0(grp_push_fu_87_tempData_data_address0);
    grp_push_fu_87->tempData_data_ce0(grp_push_fu_87_tempData_data_ce0);
    grp_push_fu_87->tempData_data_we0(grp_push_fu_87_tempData_data_we0);
    grp_push_fu_87->tempData_data_d0(grp_push_fu_87_tempData_data_d0);
    grp_push_fu_87->tempData_data_q0(grp_push_fu_87_tempData_data_q0);
    grp_push_fu_87->tempData_data_address1(grp_push_fu_87_tempData_data_address1);
    grp_push_fu_87->tempData_data_ce1(grp_push_fu_87_tempData_data_ce1);
    grp_push_fu_87->tempData_data_we1(grp_push_fu_87_tempData_data_we1);
    grp_push_fu_87->tempData_data_d1(grp_push_fu_87_tempData_data_d1);
    grp_push_fu_87->tempData_data_q1(grp_push_fu_87_tempData_data_q1);
    grp_push_fu_87->ap_return(grp_push_fu_87_ap_return);
    grp_pop_fu_104 = new pop("grp_pop_fu_104");
    grp_pop_fu_104->ap_clk(ap_clk);
    grp_pop_fu_104->ap_rst(ap_rst);
    grp_pop_fu_104->ap_start(grp_pop_fu_104_ap_start);
    grp_pop_fu_104->ap_done(grp_pop_fu_104_ap_done);
    grp_pop_fu_104->ap_idle(grp_pop_fu_104_ap_idle);
    grp_pop_fu_104->ap_ready(grp_pop_fu_104_ap_ready);
    grp_pop_fu_104->size(grp_pop_fu_104_size);
    grp_pop_fu_104->tempData_priority_address0(grp_pop_fu_104_tempData_priority_address0);
    grp_pop_fu_104->tempData_priority_ce0(grp_pop_fu_104_tempData_priority_ce0);
    grp_pop_fu_104->tempData_priority_we0(grp_pop_fu_104_tempData_priority_we0);
    grp_pop_fu_104->tempData_priority_d0(grp_pop_fu_104_tempData_priority_d0);
    grp_pop_fu_104->tempData_priority_q0(grp_pop_fu_104_tempData_priority_q0);
    grp_pop_fu_104->tempData_priority_address1(grp_pop_fu_104_tempData_priority_address1);
    grp_pop_fu_104->tempData_priority_ce1(grp_pop_fu_104_tempData_priority_ce1);
    grp_pop_fu_104->tempData_priority_we1(grp_pop_fu_104_tempData_priority_we1);
    grp_pop_fu_104->tempData_priority_d1(grp_pop_fu_104_tempData_priority_d1);
    grp_pop_fu_104->tempData_priority_q1(grp_pop_fu_104_tempData_priority_q1);
    grp_pop_fu_104->tempData_data_address0(grp_pop_fu_104_tempData_data_address0);
    grp_pop_fu_104->tempData_data_ce0(grp_pop_fu_104_tempData_data_ce0);
    grp_pop_fu_104->tempData_data_we0(grp_pop_fu_104_tempData_data_we0);
    grp_pop_fu_104->tempData_data_d0(grp_pop_fu_104_tempData_data_d0);
    grp_pop_fu_104->tempData_data_q0(grp_pop_fu_104_tempData_data_q0);
    grp_pop_fu_104->tempData_data_address1(grp_pop_fu_104_tempData_data_address1);
    grp_pop_fu_104->tempData_data_ce1(grp_pop_fu_104_tempData_data_ce1);
    grp_pop_fu_104->tempData_data_we1(grp_pop_fu_104_tempData_data_we1);
    grp_pop_fu_104->tempData_data_d1(grp_pop_fu_104_tempData_data_d1);
    grp_pop_fu_104->tempData_data_q1(grp_pop_fu_104_tempData_data_q1);
    grp_pop_fu_104->queueData_priority_address0(grp_pop_fu_104_queueData_priority_address0);
    grp_pop_fu_104->queueData_priority_ce0(grp_pop_fu_104_queueData_priority_ce0);
    grp_pop_fu_104->queueData_priority_we0(grp_pop_fu_104_queueData_priority_we0);
    grp_pop_fu_104->queueData_priority_d0(grp_pop_fu_104_queueData_priority_d0);
    grp_pop_fu_104->queueData_priority_q0(grp_pop_fu_104_queueData_priority_q0);
    grp_pop_fu_104->queueData_priority_address1(grp_pop_fu_104_queueData_priority_address1);
    grp_pop_fu_104->queueData_priority_ce1(grp_pop_fu_104_queueData_priority_ce1);
    grp_pop_fu_104->queueData_priority_we1(grp_pop_fu_104_queueData_priority_we1);
    grp_pop_fu_104->queueData_priority_d1(grp_pop_fu_104_queueData_priority_d1);
    grp_pop_fu_104->queueData_priority_q1(grp_pop_fu_104_queueData_priority_q1);
    grp_pop_fu_104->queueData_data_address0(grp_pop_fu_104_queueData_data_address0);
    grp_pop_fu_104->queueData_data_ce0(grp_pop_fu_104_queueData_data_ce0);
    grp_pop_fu_104->queueData_data_we0(grp_pop_fu_104_queueData_data_we0);
    grp_pop_fu_104->queueData_data_d0(grp_pop_fu_104_queueData_data_d0);
    grp_pop_fu_104->queueData_data_q0(grp_pop_fu_104_queueData_data_q0);
    grp_pop_fu_104->queueData_data_address1(grp_pop_fu_104_queueData_data_address1);
    grp_pop_fu_104->queueData_data_ce1(grp_pop_fu_104_queueData_data_ce1);
    grp_pop_fu_104->queueData_data_we1(grp_pop_fu_104_queueData_data_we1);
    grp_pop_fu_104->queueData_data_d1(grp_pop_fu_104_queueData_data_d1);
    grp_pop_fu_104->queueData_data_q1(grp_pop_fu_104_queueData_data_q1);
    grp_pop_fu_104->ap_return_0(grp_pop_fu_104_ap_return_0);
    grp_pop_fu_104->ap_return_1(grp_pop_fu_104_ap_return_1);
    grp_pop_fu_104->ap_return_2(grp_pop_fu_104_ap_return_2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_s_reg_211 );
    sensitive << ( tmp_reg_215 );
    sensitive << ( grp_push_fu_87_ap_done );
    sensitive << ( grp_pop_fu_104_ap_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_s_reg_211 );
    sensitive << ( tmp_reg_215 );
    sensitive << ( grp_push_fu_87_ap_done );
    sensitive << ( grp_pop_fu_104_ap_done );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_s_reg_211 );
    sensitive << ( tmp_reg_215 );
    sensitive << ( grp_push_fu_87_ap_done );
    sensitive << ( grp_pop_fu_104_ap_done );
    sensitive << ( outData_priority_2_phi_fu_58_p8 );
    sensitive << ( ap_return_0_preg );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_s_reg_211 );
    sensitive << ( tmp_reg_215 );
    sensitive << ( grp_push_fu_87_ap_done );
    sensitive << ( grp_pop_fu_104_ap_done );
    sensitive << ( outData_data_2_phi_fu_74_p8 );
    sensitive << ( ap_return_1_preg );

    SC_METHOD(thread_ap_sig_bdd_212);
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_s_reg_211 );

    SC_METHOD(thread_ap_sig_bdd_214);
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_reg_215 );

    SC_METHOD(thread_ap_sig_bdd_221);
    sensitive << ( ap_CS_fsm );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_s_reg_211 );
    sensitive << ( tmp_reg_215 );
    sensitive << ( grp_push_fu_87_ap_done );
    sensitive << ( grp_pop_fu_104_ap_done );

    SC_METHOD(thread_grp_pop_fu_104_ap_start);
    sensitive << ( grp_pop_fu_104_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_pop_fu_104_queueData_data_q0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( queueData_data_q0 );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_s_reg_211 );

    SC_METHOD(thread_grp_pop_fu_104_queueData_data_q1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( queueData_data_q1 );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_s_reg_211 );

    SC_METHOD(thread_grp_pop_fu_104_queueData_priority_q0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( queueData_priority_q0 );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_s_reg_211 );

    SC_METHOD(thread_grp_pop_fu_104_queueData_priority_q1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( queueData_priority_q1 );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_s_reg_211 );

    SC_METHOD(thread_grp_pop_fu_104_size);
    sensitive << ( ap_CS_fsm );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( size_load_reg_205 );
    sensitive << ( tmp_s_reg_211 );

    SC_METHOD(thread_grp_pop_fu_104_tempData_data_q0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tempData_data_q0 );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_s_reg_211 );

    SC_METHOD(thread_grp_pop_fu_104_tempData_data_q1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tempData_data_q1 );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_s_reg_211 );

    SC_METHOD(thread_grp_pop_fu_104_tempData_priority_q0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tempData_priority_q0 );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_s_reg_211 );

    SC_METHOD(thread_grp_pop_fu_104_tempData_priority_q1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tempData_priority_q1 );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_s_reg_211 );

    SC_METHOD(thread_grp_push_fu_87_ap_start);
    sensitive << ( grp_push_fu_87_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_push_fu_87_item_data);
    sensitive << ( ap_CS_fsm );
    sensitive << ( inData_data );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_reg_215 );

    SC_METHOD(thread_grp_push_fu_87_item_priority);
    sensitive << ( ap_CS_fsm );
    sensitive << ( inData_priority );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_reg_215 );

    SC_METHOD(thread_grp_push_fu_87_queueData_data_q0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( queueData_data_q0 );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_reg_215 );

    SC_METHOD(thread_grp_push_fu_87_queueData_data_q1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( queueData_data_q1 );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_reg_215 );

    SC_METHOD(thread_grp_push_fu_87_queueData_priority_q0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( queueData_priority_q0 );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_reg_215 );

    SC_METHOD(thread_grp_push_fu_87_queueData_priority_q1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( queueData_priority_q1 );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_reg_215 );

    SC_METHOD(thread_grp_push_fu_87_size);
    sensitive << ( ap_CS_fsm );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( size_load_reg_205 );
    sensitive << ( tmp_reg_215 );

    SC_METHOD(thread_grp_push_fu_87_tempData_data_q0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tempData_data_q0 );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_reg_215 );

    SC_METHOD(thread_grp_push_fu_87_tempData_data_q1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tempData_data_q1 );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_reg_215 );

    SC_METHOD(thread_grp_push_fu_87_tempData_priority_q0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tempData_priority_q0 );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_reg_215 );

    SC_METHOD(thread_grp_push_fu_87_tempData_priority_q1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tempData_priority_q1 );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_reg_215 );

    SC_METHOD(thread_inData_data_cast_fu_117_p1);
    sensitive << ( inData_data );

    SC_METHOD(thread_inData_priority_cast_fu_121_p1);
    sensitive << ( inData_priority );

    SC_METHOD(thread_isPush_read_read_fu_48_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( isPush );

    SC_METHOD(thread_outData_data_2_phi_fu_74_p8);
    sensitive << ( ap_CS_fsm );
    sensitive << ( inData_data_cast_reg_195 );
    sensitive << ( grp_pop_fu_104_ap_return_2 );
    sensitive << ( outData_data_2_reg_70 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_outData_priority_2_phi_fu_58_p8);
    sensitive << ( ap_CS_fsm );
    sensitive << ( inData_priority_cast_reg_200 );
    sensitive << ( grp_pop_fu_104_ap_return_1 );
    sensitive << ( outData_priority_2_reg_54 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_queueData_data_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_queueData_data_address0 );
    sensitive << ( grp_pop_fu_104_queueData_data_address0 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_queueData_data_address1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_queueData_data_address1 );
    sensitive << ( grp_pop_fu_104_queueData_data_address1 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_queueData_data_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_queueData_data_ce0 );
    sensitive << ( grp_pop_fu_104_queueData_data_ce0 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_queueData_data_ce1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_queueData_data_ce1 );
    sensitive << ( grp_pop_fu_104_queueData_data_ce1 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_queueData_data_d0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_queueData_data_d0 );
    sensitive << ( grp_pop_fu_104_queueData_data_d0 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_queueData_data_d1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_queueData_data_d1 );
    sensitive << ( grp_pop_fu_104_queueData_data_d1 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_queueData_data_we0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_queueData_data_we0 );
    sensitive << ( grp_pop_fu_104_queueData_data_we0 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_queueData_data_we1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_queueData_data_we1 );
    sensitive << ( grp_pop_fu_104_queueData_data_we1 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_queueData_priority_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_queueData_priority_address0 );
    sensitive << ( grp_pop_fu_104_queueData_priority_address0 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_queueData_priority_address1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_queueData_priority_address1 );
    sensitive << ( grp_pop_fu_104_queueData_priority_address1 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_queueData_priority_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_queueData_priority_ce0 );
    sensitive << ( grp_pop_fu_104_queueData_priority_ce0 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_queueData_priority_ce1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_queueData_priority_ce1 );
    sensitive << ( grp_pop_fu_104_queueData_priority_ce1 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_queueData_priority_d0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_queueData_priority_d0 );
    sensitive << ( grp_pop_fu_104_queueData_priority_d0 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_queueData_priority_d1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_queueData_priority_d1 );
    sensitive << ( grp_pop_fu_104_queueData_priority_d1 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_queueData_priority_we0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_queueData_priority_we0 );
    sensitive << ( grp_pop_fu_104_queueData_priority_we0 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_queueData_priority_we1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_queueData_priority_we1 );
    sensitive << ( grp_pop_fu_104_queueData_priority_we1 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_tempData_data_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_tempData_data_address0 );
    sensitive << ( grp_pop_fu_104_tempData_data_address0 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_tempData_data_address1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_tempData_data_address1 );
    sensitive << ( grp_pop_fu_104_tempData_data_address1 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_tempData_data_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_tempData_data_ce0 );
    sensitive << ( grp_pop_fu_104_tempData_data_ce0 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_tempData_data_ce1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_tempData_data_ce1 );
    sensitive << ( grp_pop_fu_104_tempData_data_ce1 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_tempData_data_d0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_tempData_data_d0 );
    sensitive << ( grp_pop_fu_104_tempData_data_d0 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_tempData_data_d1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_tempData_data_d1 );
    sensitive << ( grp_pop_fu_104_tempData_data_d1 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_tempData_data_we0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_tempData_data_we0 );
    sensitive << ( grp_pop_fu_104_tempData_data_we0 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_tempData_data_we1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_tempData_data_we1 );
    sensitive << ( grp_pop_fu_104_tempData_data_we1 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_tempData_priority_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_tempData_priority_address0 );
    sensitive << ( grp_pop_fu_104_tempData_priority_address0 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_tempData_priority_address1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_tempData_priority_address1 );
    sensitive << ( grp_pop_fu_104_tempData_priority_address1 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_tempData_priority_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_tempData_priority_ce0 );
    sensitive << ( grp_pop_fu_104_tempData_priority_ce0 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_tempData_priority_ce1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_tempData_priority_ce1 );
    sensitive << ( grp_pop_fu_104_tempData_priority_ce1 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_tempData_priority_d0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_tempData_priority_d0 );
    sensitive << ( grp_pop_fu_104_tempData_priority_d0 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_tempData_priority_d1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_tempData_priority_d1 );
    sensitive << ( grp_pop_fu_104_tempData_priority_d1 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_tempData_priority_we0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_tempData_priority_we0 );
    sensitive << ( grp_pop_fu_104_tempData_priority_we0 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_tempData_priority_we1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_push_fu_87_tempData_priority_we1 );
    sensitive << ( grp_pop_fu_104_tempData_priority_we1 );
    sensitive << ( ap_sig_bdd_214 );
    sensitive << ( ap_sig_bdd_212 );

    SC_METHOD(thread_tmp_fu_137_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( size );
    sensitive << ( isPush_read_read_fu_48_p2 );

    SC_METHOD(thread_tmp_s_fu_131_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( size );
    sensitive << ( isPush_read_read_fu_48_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( isPush_read_read_fu_48_p2 );
    sensitive << ( tmp_s_reg_211 );
    sensitive << ( tmp_reg_215 );
    sensitive << ( grp_push_fu_87_ap_done );
    sensitive << ( grp_pop_fu_104_ap_done );

    ap_CS_fsm = "0";
    size = "00000000000000000000000000000000";
    grp_push_fu_87_ap_start_ap_start_reg = SC_LOGIC_0;
    grp_pop_fu_104_ap_start_ap_start_reg = SC_LOGIC_0;
    ap_return_0_preg = "00000000000000000000000000000000";
    ap_return_1_preg = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "queue_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, isPush, "(port)isPush");
    sc_trace(mVcdFile, inData_priority, "(port)inData_priority");
    sc_trace(mVcdFile, inData_data, "(port)inData_data");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, size, "size");
    sc_trace(mVcdFile, queueData_priority_address0, "queueData_priority_address0");
    sc_trace(mVcdFile, queueData_priority_ce0, "queueData_priority_ce0");
    sc_trace(mVcdFile, queueData_priority_we0, "queueData_priority_we0");
    sc_trace(mVcdFile, queueData_priority_d0, "queueData_priority_d0");
    sc_trace(mVcdFile, queueData_priority_q0, "queueData_priority_q0");
    sc_trace(mVcdFile, queueData_priority_address1, "queueData_priority_address1");
    sc_trace(mVcdFile, queueData_priority_ce1, "queueData_priority_ce1");
    sc_trace(mVcdFile, queueData_priority_we1, "queueData_priority_we1");
    sc_trace(mVcdFile, queueData_priority_d1, "queueData_priority_d1");
    sc_trace(mVcdFile, queueData_priority_q1, "queueData_priority_q1");
    sc_trace(mVcdFile, queueData_data_address0, "queueData_data_address0");
    sc_trace(mVcdFile, queueData_data_ce0, "queueData_data_ce0");
    sc_trace(mVcdFile, queueData_data_we0, "queueData_data_we0");
    sc_trace(mVcdFile, queueData_data_d0, "queueData_data_d0");
    sc_trace(mVcdFile, queueData_data_q0, "queueData_data_q0");
    sc_trace(mVcdFile, queueData_data_address1, "queueData_data_address1");
    sc_trace(mVcdFile, queueData_data_ce1, "queueData_data_ce1");
    sc_trace(mVcdFile, queueData_data_we1, "queueData_data_we1");
    sc_trace(mVcdFile, queueData_data_d1, "queueData_data_d1");
    sc_trace(mVcdFile, queueData_data_q1, "queueData_data_q1");
    sc_trace(mVcdFile, tempData_priority_address0, "tempData_priority_address0");
    sc_trace(mVcdFile, tempData_priority_ce0, "tempData_priority_ce0");
    sc_trace(mVcdFile, tempData_priority_we0, "tempData_priority_we0");
    sc_trace(mVcdFile, tempData_priority_d0, "tempData_priority_d0");
    sc_trace(mVcdFile, tempData_priority_q0, "tempData_priority_q0");
    sc_trace(mVcdFile, tempData_priority_address1, "tempData_priority_address1");
    sc_trace(mVcdFile, tempData_priority_ce1, "tempData_priority_ce1");
    sc_trace(mVcdFile, tempData_priority_we1, "tempData_priority_we1");
    sc_trace(mVcdFile, tempData_priority_d1, "tempData_priority_d1");
    sc_trace(mVcdFile, tempData_priority_q1, "tempData_priority_q1");
    sc_trace(mVcdFile, tempData_data_address0, "tempData_data_address0");
    sc_trace(mVcdFile, tempData_data_ce0, "tempData_data_ce0");
    sc_trace(mVcdFile, tempData_data_we0, "tempData_data_we0");
    sc_trace(mVcdFile, tempData_data_d0, "tempData_data_d0");
    sc_trace(mVcdFile, tempData_data_q0, "tempData_data_q0");
    sc_trace(mVcdFile, tempData_data_address1, "tempData_data_address1");
    sc_trace(mVcdFile, tempData_data_ce1, "tempData_data_ce1");
    sc_trace(mVcdFile, tempData_data_we1, "tempData_data_we1");
    sc_trace(mVcdFile, tempData_data_d1, "tempData_data_d1");
    sc_trace(mVcdFile, tempData_data_q1, "tempData_data_q1");
    sc_trace(mVcdFile, isPush_read_read_fu_48_p2, "isPush_read_read_fu_48_p2");
    sc_trace(mVcdFile, inData_data_cast_fu_117_p1, "inData_data_cast_fu_117_p1");
    sc_trace(mVcdFile, inData_data_cast_reg_195, "inData_data_cast_reg_195");
    sc_trace(mVcdFile, inData_priority_cast_fu_121_p1, "inData_priority_cast_fu_121_p1");
    sc_trace(mVcdFile, inData_priority_cast_reg_200, "inData_priority_cast_reg_200");
    sc_trace(mVcdFile, size_load_reg_205, "size_load_reg_205");
    sc_trace(mVcdFile, tmp_s_fu_131_p2, "tmp_s_fu_131_p2");
    sc_trace(mVcdFile, tmp_s_reg_211, "tmp_s_reg_211");
    sc_trace(mVcdFile, tmp_fu_137_p2, "tmp_fu_137_p2");
    sc_trace(mVcdFile, tmp_reg_215, "tmp_reg_215");
    sc_trace(mVcdFile, grp_push_fu_87_ap_start, "grp_push_fu_87_ap_start");
    sc_trace(mVcdFile, grp_push_fu_87_ap_done, "grp_push_fu_87_ap_done");
    sc_trace(mVcdFile, grp_push_fu_87_ap_idle, "grp_push_fu_87_ap_idle");
    sc_trace(mVcdFile, grp_push_fu_87_ap_ready, "grp_push_fu_87_ap_ready");
    sc_trace(mVcdFile, grp_push_fu_87_queueData_priority_address0, "grp_push_fu_87_queueData_priority_address0");
    sc_trace(mVcdFile, grp_push_fu_87_queueData_priority_ce0, "grp_push_fu_87_queueData_priority_ce0");
    sc_trace(mVcdFile, grp_push_fu_87_queueData_priority_we0, "grp_push_fu_87_queueData_priority_we0");
    sc_trace(mVcdFile, grp_push_fu_87_queueData_priority_d0, "grp_push_fu_87_queueData_priority_d0");
    sc_trace(mVcdFile, grp_push_fu_87_queueData_priority_q0, "grp_push_fu_87_queueData_priority_q0");
    sc_trace(mVcdFile, grp_push_fu_87_queueData_priority_address1, "grp_push_fu_87_queueData_priority_address1");
    sc_trace(mVcdFile, grp_push_fu_87_queueData_priority_ce1, "grp_push_fu_87_queueData_priority_ce1");
    sc_trace(mVcdFile, grp_push_fu_87_queueData_priority_we1, "grp_push_fu_87_queueData_priority_we1");
    sc_trace(mVcdFile, grp_push_fu_87_queueData_priority_d1, "grp_push_fu_87_queueData_priority_d1");
    sc_trace(mVcdFile, grp_push_fu_87_queueData_priority_q1, "grp_push_fu_87_queueData_priority_q1");
    sc_trace(mVcdFile, grp_push_fu_87_queueData_data_address0, "grp_push_fu_87_queueData_data_address0");
    sc_trace(mVcdFile, grp_push_fu_87_queueData_data_ce0, "grp_push_fu_87_queueData_data_ce0");
    sc_trace(mVcdFile, grp_push_fu_87_queueData_data_we0, "grp_push_fu_87_queueData_data_we0");
    sc_trace(mVcdFile, grp_push_fu_87_queueData_data_d0, "grp_push_fu_87_queueData_data_d0");
    sc_trace(mVcdFile, grp_push_fu_87_queueData_data_q0, "grp_push_fu_87_queueData_data_q0");
    sc_trace(mVcdFile, grp_push_fu_87_queueData_data_address1, "grp_push_fu_87_queueData_data_address1");
    sc_trace(mVcdFile, grp_push_fu_87_queueData_data_ce1, "grp_push_fu_87_queueData_data_ce1");
    sc_trace(mVcdFile, grp_push_fu_87_queueData_data_we1, "grp_push_fu_87_queueData_data_we1");
    sc_trace(mVcdFile, grp_push_fu_87_queueData_data_d1, "grp_push_fu_87_queueData_data_d1");
    sc_trace(mVcdFile, grp_push_fu_87_queueData_data_q1, "grp_push_fu_87_queueData_data_q1");
    sc_trace(mVcdFile, grp_push_fu_87_size, "grp_push_fu_87_size");
    sc_trace(mVcdFile, grp_push_fu_87_item_priority, "grp_push_fu_87_item_priority");
    sc_trace(mVcdFile, grp_push_fu_87_item_data, "grp_push_fu_87_item_data");
    sc_trace(mVcdFile, grp_push_fu_87_tempData_priority_address0, "grp_push_fu_87_tempData_priority_address0");
    sc_trace(mVcdFile, grp_push_fu_87_tempData_priority_ce0, "grp_push_fu_87_tempData_priority_ce0");
    sc_trace(mVcdFile, grp_push_fu_87_tempData_priority_we0, "grp_push_fu_87_tempData_priority_we0");
    sc_trace(mVcdFile, grp_push_fu_87_tempData_priority_d0, "grp_push_fu_87_tempData_priority_d0");
    sc_trace(mVcdFile, grp_push_fu_87_tempData_priority_q0, "grp_push_fu_87_tempData_priority_q0");
    sc_trace(mVcdFile, grp_push_fu_87_tempData_priority_address1, "grp_push_fu_87_tempData_priority_address1");
    sc_trace(mVcdFile, grp_push_fu_87_tempData_priority_ce1, "grp_push_fu_87_tempData_priority_ce1");
    sc_trace(mVcdFile, grp_push_fu_87_tempData_priority_we1, "grp_push_fu_87_tempData_priority_we1");
    sc_trace(mVcdFile, grp_push_fu_87_tempData_priority_d1, "grp_push_fu_87_tempData_priority_d1");
    sc_trace(mVcdFile, grp_push_fu_87_tempData_priority_q1, "grp_push_fu_87_tempData_priority_q1");
    sc_trace(mVcdFile, grp_push_fu_87_tempData_data_address0, "grp_push_fu_87_tempData_data_address0");
    sc_trace(mVcdFile, grp_push_fu_87_tempData_data_ce0, "grp_push_fu_87_tempData_data_ce0");
    sc_trace(mVcdFile, grp_push_fu_87_tempData_data_we0, "grp_push_fu_87_tempData_data_we0");
    sc_trace(mVcdFile, grp_push_fu_87_tempData_data_d0, "grp_push_fu_87_tempData_data_d0");
    sc_trace(mVcdFile, grp_push_fu_87_tempData_data_q0, "grp_push_fu_87_tempData_data_q0");
    sc_trace(mVcdFile, grp_push_fu_87_tempData_data_address1, "grp_push_fu_87_tempData_data_address1");
    sc_trace(mVcdFile, grp_push_fu_87_tempData_data_ce1, "grp_push_fu_87_tempData_data_ce1");
    sc_trace(mVcdFile, grp_push_fu_87_tempData_data_we1, "grp_push_fu_87_tempData_data_we1");
    sc_trace(mVcdFile, grp_push_fu_87_tempData_data_d1, "grp_push_fu_87_tempData_data_d1");
    sc_trace(mVcdFile, grp_push_fu_87_tempData_data_q1, "grp_push_fu_87_tempData_data_q1");
    sc_trace(mVcdFile, grp_push_fu_87_ap_return, "grp_push_fu_87_ap_return");
    sc_trace(mVcdFile, grp_pop_fu_104_ap_start, "grp_pop_fu_104_ap_start");
    sc_trace(mVcdFile, grp_pop_fu_104_ap_done, "grp_pop_fu_104_ap_done");
    sc_trace(mVcdFile, grp_pop_fu_104_ap_idle, "grp_pop_fu_104_ap_idle");
    sc_trace(mVcdFile, grp_pop_fu_104_ap_ready, "grp_pop_fu_104_ap_ready");
    sc_trace(mVcdFile, grp_pop_fu_104_size, "grp_pop_fu_104_size");
    sc_trace(mVcdFile, grp_pop_fu_104_tempData_priority_address0, "grp_pop_fu_104_tempData_priority_address0");
    sc_trace(mVcdFile, grp_pop_fu_104_tempData_priority_ce0, "grp_pop_fu_104_tempData_priority_ce0");
    sc_trace(mVcdFile, grp_pop_fu_104_tempData_priority_we0, "grp_pop_fu_104_tempData_priority_we0");
    sc_trace(mVcdFile, grp_pop_fu_104_tempData_priority_d0, "grp_pop_fu_104_tempData_priority_d0");
    sc_trace(mVcdFile, grp_pop_fu_104_tempData_priority_q0, "grp_pop_fu_104_tempData_priority_q0");
    sc_trace(mVcdFile, grp_pop_fu_104_tempData_priority_address1, "grp_pop_fu_104_tempData_priority_address1");
    sc_trace(mVcdFile, grp_pop_fu_104_tempData_priority_ce1, "grp_pop_fu_104_tempData_priority_ce1");
    sc_trace(mVcdFile, grp_pop_fu_104_tempData_priority_we1, "grp_pop_fu_104_tempData_priority_we1");
    sc_trace(mVcdFile, grp_pop_fu_104_tempData_priority_d1, "grp_pop_fu_104_tempData_priority_d1");
    sc_trace(mVcdFile, grp_pop_fu_104_tempData_priority_q1, "grp_pop_fu_104_tempData_priority_q1");
    sc_trace(mVcdFile, grp_pop_fu_104_tempData_data_address0, "grp_pop_fu_104_tempData_data_address0");
    sc_trace(mVcdFile, grp_pop_fu_104_tempData_data_ce0, "grp_pop_fu_104_tempData_data_ce0");
    sc_trace(mVcdFile, grp_pop_fu_104_tempData_data_we0, "grp_pop_fu_104_tempData_data_we0");
    sc_trace(mVcdFile, grp_pop_fu_104_tempData_data_d0, "grp_pop_fu_104_tempData_data_d0");
    sc_trace(mVcdFile, grp_pop_fu_104_tempData_data_q0, "grp_pop_fu_104_tempData_data_q0");
    sc_trace(mVcdFile, grp_pop_fu_104_tempData_data_address1, "grp_pop_fu_104_tempData_data_address1");
    sc_trace(mVcdFile, grp_pop_fu_104_tempData_data_ce1, "grp_pop_fu_104_tempData_data_ce1");
    sc_trace(mVcdFile, grp_pop_fu_104_tempData_data_we1, "grp_pop_fu_104_tempData_data_we1");
    sc_trace(mVcdFile, grp_pop_fu_104_tempData_data_d1, "grp_pop_fu_104_tempData_data_d1");
    sc_trace(mVcdFile, grp_pop_fu_104_tempData_data_q1, "grp_pop_fu_104_tempData_data_q1");
    sc_trace(mVcdFile, grp_pop_fu_104_queueData_priority_address0, "grp_pop_fu_104_queueData_priority_address0");
    sc_trace(mVcdFile, grp_pop_fu_104_queueData_priority_ce0, "grp_pop_fu_104_queueData_priority_ce0");
    sc_trace(mVcdFile, grp_pop_fu_104_queueData_priority_we0, "grp_pop_fu_104_queueData_priority_we0");
    sc_trace(mVcdFile, grp_pop_fu_104_queueData_priority_d0, "grp_pop_fu_104_queueData_priority_d0");
    sc_trace(mVcdFile, grp_pop_fu_104_queueData_priority_q0, "grp_pop_fu_104_queueData_priority_q0");
    sc_trace(mVcdFile, grp_pop_fu_104_queueData_priority_address1, "grp_pop_fu_104_queueData_priority_address1");
    sc_trace(mVcdFile, grp_pop_fu_104_queueData_priority_ce1, "grp_pop_fu_104_queueData_priority_ce1");
    sc_trace(mVcdFile, grp_pop_fu_104_queueData_priority_we1, "grp_pop_fu_104_queueData_priority_we1");
    sc_trace(mVcdFile, grp_pop_fu_104_queueData_priority_d1, "grp_pop_fu_104_queueData_priority_d1");
    sc_trace(mVcdFile, grp_pop_fu_104_queueData_priority_q1, "grp_pop_fu_104_queueData_priority_q1");
    sc_trace(mVcdFile, grp_pop_fu_104_queueData_data_address0, "grp_pop_fu_104_queueData_data_address0");
    sc_trace(mVcdFile, grp_pop_fu_104_queueData_data_ce0, "grp_pop_fu_104_queueData_data_ce0");
    sc_trace(mVcdFile, grp_pop_fu_104_queueData_data_we0, "grp_pop_fu_104_queueData_data_we0");
    sc_trace(mVcdFile, grp_pop_fu_104_queueData_data_d0, "grp_pop_fu_104_queueData_data_d0");
    sc_trace(mVcdFile, grp_pop_fu_104_queueData_data_q0, "grp_pop_fu_104_queueData_data_q0");
    sc_trace(mVcdFile, grp_pop_fu_104_queueData_data_address1, "grp_pop_fu_104_queueData_data_address1");
    sc_trace(mVcdFile, grp_pop_fu_104_queueData_data_ce1, "grp_pop_fu_104_queueData_data_ce1");
    sc_trace(mVcdFile, grp_pop_fu_104_queueData_data_we1, "grp_pop_fu_104_queueData_data_we1");
    sc_trace(mVcdFile, grp_pop_fu_104_queueData_data_d1, "grp_pop_fu_104_queueData_data_d1");
    sc_trace(mVcdFile, grp_pop_fu_104_queueData_data_q1, "grp_pop_fu_104_queueData_data_q1");
    sc_trace(mVcdFile, grp_pop_fu_104_ap_return_0, "grp_pop_fu_104_ap_return_0");
    sc_trace(mVcdFile, grp_pop_fu_104_ap_return_1, "grp_pop_fu_104_ap_return_1");
    sc_trace(mVcdFile, grp_pop_fu_104_ap_return_2, "grp_pop_fu_104_ap_return_2");
    sc_trace(mVcdFile, outData_priority_2_phi_fu_58_p8, "outData_priority_2_phi_fu_58_p8");
    sc_trace(mVcdFile, outData_priority_2_reg_54, "outData_priority_2_reg_54");
    sc_trace(mVcdFile, outData_data_2_phi_fu_74_p8, "outData_data_2_phi_fu_74_p8");
    sc_trace(mVcdFile, outData_data_2_reg_70, "outData_data_2_reg_70");
    sc_trace(mVcdFile, grp_push_fu_87_ap_start_ap_start_reg, "grp_push_fu_87_ap_start_ap_start_reg");
    sc_trace(mVcdFile, grp_pop_fu_104_ap_start_ap_start_reg, "grp_pop_fu_104_ap_start_ap_start_reg");
    sc_trace(mVcdFile, ap_return_0_preg, "ap_return_0_preg");
    sc_trace(mVcdFile, ap_return_1_preg, "ap_return_1_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_bdd_214, "ap_sig_bdd_214");
    sc_trace(mVcdFile, ap_sig_bdd_212, "ap_sig_bdd_212");
    sc_trace(mVcdFile, ap_sig_bdd_221, "ap_sig_bdd_221");
#endif

    }
}

queue::~queue() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete queueData_priority_U;
    delete queueData_data_U;
    delete tempData_priority_U;
    delete tempData_data_U;
    delete grp_push_fu_87;
    delete grp_pop_fu_104;
}

void queue::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_0_preg = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
             !((esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(tmp_s_reg_211.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_pop_fu_104_ap_done.read())) || (!esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_reg_215.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_push_fu_87_ap_done.read()))))) {
            ap_return_0_preg = outData_priority_2_phi_fu_58_p8.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_1_preg = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
             !((esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(tmp_s_reg_211.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_pop_fu_104_ap_done.read())) || (!esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_reg_215.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_push_fu_87_ap_done.read()))))) {
            ap_return_1_preg = outData_data_2_phi_fu_74_p8.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_pop_fu_104_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
             !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
             esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
             esl_seteq<1,1,1>(tmp_s_fu_131_p2.read(), ap_const_lv1_0))) {
            grp_pop_fu_104_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_pop_fu_104_ap_ready.read())) {
            grp_pop_fu_104_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_push_fu_87_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
             !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
             !esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_137_p2.read()))) {
            grp_push_fu_87_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_push_fu_87_ap_ready.read())) {
            grp_push_fu_87_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
    if (((esl_seteq<1,1,1>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
          !esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_137_p2.read())) || 
         (esl_seteq<1,1,1>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
          esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
          !esl_seteq<1,1,1>(tmp_s_fu_131_p2.read(), ap_const_lv1_0)))) {
        outData_data_2_reg_70 = ap_const_lv32_FFFFFFFF;
    } else if ((esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(tmp_s_reg_211.read(), ap_const_lv1_0) && 
                !((esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(tmp_s_reg_211.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_pop_fu_104_ap_done.read())) || (!esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_reg_215.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_push_fu_87_ap_done.read()))))) {
        outData_data_2_reg_70 = grp_pop_fu_104_ap_return_2.read();
    } else if ((!esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_reg_215.read()) && 
                !((esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(tmp_s_reg_211.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_pop_fu_104_ap_done.read())) || (!esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_reg_215.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_push_fu_87_ap_done.read()))))) {
        outData_data_2_reg_70 = inData_data_cast_reg_195.read();
    }
    if (((esl_seteq<1,1,1>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
          !esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_137_p2.read())) || 
         (esl_seteq<1,1,1>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
          esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
          !esl_seteq<1,1,1>(tmp_s_fu_131_p2.read(), ap_const_lv1_0)))) {
        outData_priority_2_reg_54 = ap_const_lv32_7FFFFFFF;
    } else if ((esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(tmp_s_reg_211.read(), ap_const_lv1_0) && 
                !((esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(tmp_s_reg_211.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_pop_fu_104_ap_done.read())) || (!esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_reg_215.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_push_fu_87_ap_done.read()))))) {
        outData_priority_2_reg_54 = grp_pop_fu_104_ap_return_1.read();
    } else if ((!esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_reg_215.read()) && 
                !((esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(tmp_s_reg_211.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_pop_fu_104_ap_done.read())) || (!esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_reg_215.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_push_fu_87_ap_done.read()))))) {
        outData_priority_2_reg_54 = inData_priority_cast_reg_200.read();
    }
    if (ap_sig_bdd_221.read()) {
        if (ap_sig_bdd_214.read()) {
            size = grp_push_fu_87_ap_return.read();
        } else if (ap_sig_bdd_212.read()) {
            size = grp_pop_fu_104_ap_return_0.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        inData_data_cast_reg_195 = inData_data_cast_fu_117_p1.read();
        inData_priority_cast_reg_200 = inData_priority_cast_fu_121_p1.read();
        size_load_reg_205 = size.read();
    }
    if ((esl_seteq<1,1,1>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && !esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0))) {
        tmp_reg_215 = tmp_fu_137_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0))) {
        tmp_s_reg_211 = tmp_s_fu_131_p2.read();
    }
}

void queue::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_ST_st1_fsm_0, ap_CS_fsm.read())) || 
         (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
          !((esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(tmp_s_reg_211.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_pop_fu_104_ap_done.read())) || (!esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_reg_215.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_push_fu_87_ap_done.read())))))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void queue::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_ST_st1_fsm_0, ap_CS_fsm.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void queue::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
         !((esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(tmp_s_reg_211.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_pop_fu_104_ap_done.read())) || (!esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_reg_215.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_push_fu_87_ap_done.read()))))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void queue::thread_ap_return_0() {
    if ((esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
         !((esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(tmp_s_reg_211.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_pop_fu_104_ap_done.read())) || (!esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_reg_215.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_push_fu_87_ap_done.read()))))) {
        ap_return_0 = outData_priority_2_phi_fu_58_p8.read();
    } else {
        ap_return_0 = ap_return_0_preg.read();
    }
}

void queue::thread_ap_return_1() {
    if ((esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
         !((esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(tmp_s_reg_211.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_pop_fu_104_ap_done.read())) || (!esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_reg_215.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_push_fu_87_ap_done.read()))))) {
        ap_return_1 = outData_data_2_phi_fu_74_p8.read();
    } else {
        ap_return_1 = ap_return_1_preg.read();
    }
}

void queue::thread_ap_sig_bdd_212() {
    ap_sig_bdd_212 = (esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_s_reg_211.read(), ap_const_lv1_0));
}

void queue::thread_ap_sig_bdd_214() {
    ap_sig_bdd_214 = (!esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_reg_215.read()));
}

void queue::thread_ap_sig_bdd_221() {
    ap_sig_bdd_221 = (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && !((esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(tmp_s_reg_211.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_pop_fu_104_ap_done.read())) || (!esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_reg_215.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_push_fu_87_ap_done.read()))));
}

void queue::thread_grp_pop_fu_104_ap_start() {
    grp_pop_fu_104_ap_start = grp_pop_fu_104_ap_start_ap_start_reg.read();
}

void queue::thread_grp_pop_fu_104_queueData_data_q0() {
    grp_pop_fu_104_queueData_data_q0 = queueData_data_q0.read();
}

void queue::thread_grp_pop_fu_104_queueData_data_q1() {
    grp_pop_fu_104_queueData_data_q1 = queueData_data_q1.read();
}

void queue::thread_grp_pop_fu_104_queueData_priority_q0() {
    grp_pop_fu_104_queueData_priority_q0 = queueData_priority_q0.read();
}

void queue::thread_grp_pop_fu_104_queueData_priority_q1() {
    grp_pop_fu_104_queueData_priority_q1 = queueData_priority_q1.read();
}

void queue::thread_grp_pop_fu_104_size() {
    grp_pop_fu_104_size = size_load_reg_205.read();
}

void queue::thread_grp_pop_fu_104_tempData_data_q0() {
    grp_pop_fu_104_tempData_data_q0 = tempData_data_q0.read();
}

void queue::thread_grp_pop_fu_104_tempData_data_q1() {
    grp_pop_fu_104_tempData_data_q1 = tempData_data_q1.read();
}

void queue::thread_grp_pop_fu_104_tempData_priority_q0() {
    grp_pop_fu_104_tempData_priority_q0 = tempData_priority_q0.read();
}

void queue::thread_grp_pop_fu_104_tempData_priority_q1() {
    grp_pop_fu_104_tempData_priority_q1 = tempData_priority_q1.read();
}

void queue::thread_grp_push_fu_87_ap_start() {
    grp_push_fu_87_ap_start = grp_push_fu_87_ap_start_ap_start_reg.read();
}

void queue::thread_grp_push_fu_87_item_data() {
    grp_push_fu_87_item_data = inData_data.read();
}

void queue::thread_grp_push_fu_87_item_priority() {
    grp_push_fu_87_item_priority = inData_priority.read();
}

void queue::thread_grp_push_fu_87_queueData_data_q0() {
    grp_push_fu_87_queueData_data_q0 = queueData_data_q0.read();
}

void queue::thread_grp_push_fu_87_queueData_data_q1() {
    grp_push_fu_87_queueData_data_q1 = queueData_data_q1.read();
}

void queue::thread_grp_push_fu_87_queueData_priority_q0() {
    grp_push_fu_87_queueData_priority_q0 = queueData_priority_q0.read();
}

void queue::thread_grp_push_fu_87_queueData_priority_q1() {
    grp_push_fu_87_queueData_priority_q1 = queueData_priority_q1.read();
}

void queue::thread_grp_push_fu_87_size() {
    grp_push_fu_87_size = size_load_reg_205.read();
}

void queue::thread_grp_push_fu_87_tempData_data_q0() {
    grp_push_fu_87_tempData_data_q0 = tempData_data_q0.read();
}

void queue::thread_grp_push_fu_87_tempData_data_q1() {
    grp_push_fu_87_tempData_data_q1 = tempData_data_q1.read();
}

void queue::thread_grp_push_fu_87_tempData_priority_q0() {
    grp_push_fu_87_tempData_priority_q0 = tempData_priority_q0.read();
}

void queue::thread_grp_push_fu_87_tempData_priority_q1() {
    grp_push_fu_87_tempData_priority_q1 = tempData_priority_q1.read();
}

void queue::thread_inData_data_cast_fu_117_p1() {
    inData_data_cast_fu_117_p1 = esl_zext<32,8>(inData_data.read());
}

void queue::thread_inData_priority_cast_fu_121_p1() {
    inData_priority_cast_fu_121_p1 = esl_zext<32,9>(inData_priority.read());
}

void queue::thread_isPush_read_read_fu_48_p2() {
    isPush_read_read_fu_48_p2 =  (sc_lv<1>) (isPush.read());
}

void queue::thread_outData_data_2_phi_fu_74_p8() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            outData_data_2_phi_fu_74_p8 = grp_pop_fu_104_ap_return_2.read();
        } else if (ap_sig_bdd_214.read()) {
            outData_data_2_phi_fu_74_p8 = inData_data_cast_reg_195.read();
        } else {
            outData_data_2_phi_fu_74_p8 = outData_data_2_reg_70.read();
        }
    } else {
        outData_data_2_phi_fu_74_p8 = outData_data_2_reg_70.read();
    }
}

void queue::thread_outData_priority_2_phi_fu_58_p8() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            outData_priority_2_phi_fu_58_p8 = grp_pop_fu_104_ap_return_1.read();
        } else if (ap_sig_bdd_214.read()) {
            outData_priority_2_phi_fu_58_p8 = inData_priority_cast_reg_200.read();
        } else {
            outData_priority_2_phi_fu_58_p8 = outData_priority_2_reg_54.read();
        }
    } else {
        outData_priority_2_phi_fu_58_p8 = outData_priority_2_reg_54.read();
    }
}

void queue::thread_queueData_data_address0() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            queueData_data_address0 = grp_pop_fu_104_queueData_data_address0.read();
        } else if (ap_sig_bdd_214.read()) {
            queueData_data_address0 = grp_push_fu_87_queueData_data_address0.read();
        } else {
            queueData_data_address0 = "XXXXXXXXX";
        }
    } else {
        queueData_data_address0 = "XXXXXXXXX";
    }
}

void queue::thread_queueData_data_address1() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            queueData_data_address1 = grp_pop_fu_104_queueData_data_address1.read();
        } else if (ap_sig_bdd_214.read()) {
            queueData_data_address1 = grp_push_fu_87_queueData_data_address1.read();
        } else {
            queueData_data_address1 = "XXXXXXXXX";
        }
    } else {
        queueData_data_address1 = "XXXXXXXXX";
    }
}

void queue::thread_queueData_data_ce0() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            queueData_data_ce0 = grp_pop_fu_104_queueData_data_ce0.read();
        } else if (ap_sig_bdd_214.read()) {
            queueData_data_ce0 = grp_push_fu_87_queueData_data_ce0.read();
        } else {
            queueData_data_ce0 = ap_const_logic_0;
        }
    } else {
        queueData_data_ce0 = ap_const_logic_0;
    }
}

void queue::thread_queueData_data_ce1() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            queueData_data_ce1 = grp_pop_fu_104_queueData_data_ce1.read();
        } else if (ap_sig_bdd_214.read()) {
            queueData_data_ce1 = grp_push_fu_87_queueData_data_ce1.read();
        } else {
            queueData_data_ce1 = ap_const_logic_0;
        }
    } else {
        queueData_data_ce1 = ap_const_logic_0;
    }
}

void queue::thread_queueData_data_d0() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            queueData_data_d0 = grp_pop_fu_104_queueData_data_d0.read();
        } else if (ap_sig_bdd_214.read()) {
            queueData_data_d0 = grp_push_fu_87_queueData_data_d0.read();
        } else {
            queueData_data_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        queueData_data_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void queue::thread_queueData_data_d1() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            queueData_data_d1 = grp_pop_fu_104_queueData_data_d1.read();
        } else if (ap_sig_bdd_214.read()) {
            queueData_data_d1 = grp_push_fu_87_queueData_data_d1.read();
        } else {
            queueData_data_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        queueData_data_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void queue::thread_queueData_data_we0() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            queueData_data_we0 = grp_pop_fu_104_queueData_data_we0.read();
        } else if (ap_sig_bdd_214.read()) {
            queueData_data_we0 = grp_push_fu_87_queueData_data_we0.read();
        } else {
            queueData_data_we0 = ap_const_logic_0;
        }
    } else {
        queueData_data_we0 = ap_const_logic_0;
    }
}

void queue::thread_queueData_data_we1() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            queueData_data_we1 = grp_pop_fu_104_queueData_data_we1.read();
        } else if (ap_sig_bdd_214.read()) {
            queueData_data_we1 = grp_push_fu_87_queueData_data_we1.read();
        } else {
            queueData_data_we1 = ap_const_logic_0;
        }
    } else {
        queueData_data_we1 = ap_const_logic_0;
    }
}

void queue::thread_queueData_priority_address0() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            queueData_priority_address0 = grp_pop_fu_104_queueData_priority_address0.read();
        } else if (ap_sig_bdd_214.read()) {
            queueData_priority_address0 = grp_push_fu_87_queueData_priority_address0.read();
        } else {
            queueData_priority_address0 = "XXXXXXXXX";
        }
    } else {
        queueData_priority_address0 = "XXXXXXXXX";
    }
}

void queue::thread_queueData_priority_address1() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            queueData_priority_address1 = grp_pop_fu_104_queueData_priority_address1.read();
        } else if (ap_sig_bdd_214.read()) {
            queueData_priority_address1 = grp_push_fu_87_queueData_priority_address1.read();
        } else {
            queueData_priority_address1 = "XXXXXXXXX";
        }
    } else {
        queueData_priority_address1 = "XXXXXXXXX";
    }
}

void queue::thread_queueData_priority_ce0() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            queueData_priority_ce0 = grp_pop_fu_104_queueData_priority_ce0.read();
        } else if (ap_sig_bdd_214.read()) {
            queueData_priority_ce0 = grp_push_fu_87_queueData_priority_ce0.read();
        } else {
            queueData_priority_ce0 = ap_const_logic_0;
        }
    } else {
        queueData_priority_ce0 = ap_const_logic_0;
    }
}

void queue::thread_queueData_priority_ce1() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            queueData_priority_ce1 = grp_pop_fu_104_queueData_priority_ce1.read();
        } else if (ap_sig_bdd_214.read()) {
            queueData_priority_ce1 = grp_push_fu_87_queueData_priority_ce1.read();
        } else {
            queueData_priority_ce1 = ap_const_logic_0;
        }
    } else {
        queueData_priority_ce1 = ap_const_logic_0;
    }
}

void queue::thread_queueData_priority_d0() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            queueData_priority_d0 = grp_pop_fu_104_queueData_priority_d0.read();
        } else if (ap_sig_bdd_214.read()) {
            queueData_priority_d0 = grp_push_fu_87_queueData_priority_d0.read();
        } else {
            queueData_priority_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        queueData_priority_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void queue::thread_queueData_priority_d1() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            queueData_priority_d1 = grp_pop_fu_104_queueData_priority_d1.read();
        } else if (ap_sig_bdd_214.read()) {
            queueData_priority_d1 = grp_push_fu_87_queueData_priority_d1.read();
        } else {
            queueData_priority_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        queueData_priority_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void queue::thread_queueData_priority_we0() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            queueData_priority_we0 = grp_pop_fu_104_queueData_priority_we0.read();
        } else if (ap_sig_bdd_214.read()) {
            queueData_priority_we0 = grp_push_fu_87_queueData_priority_we0.read();
        } else {
            queueData_priority_we0 = ap_const_logic_0;
        }
    } else {
        queueData_priority_we0 = ap_const_logic_0;
    }
}

void queue::thread_queueData_priority_we1() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            queueData_priority_we1 = grp_pop_fu_104_queueData_priority_we1.read();
        } else if (ap_sig_bdd_214.read()) {
            queueData_priority_we1 = grp_push_fu_87_queueData_priority_we1.read();
        } else {
            queueData_priority_we1 = ap_const_logic_0;
        }
    } else {
        queueData_priority_we1 = ap_const_logic_0;
    }
}

void queue::thread_tempData_data_address0() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            tempData_data_address0 = grp_pop_fu_104_tempData_data_address0.read();
        } else if (ap_sig_bdd_214.read()) {
            tempData_data_address0 = grp_push_fu_87_tempData_data_address0.read();
        } else {
            tempData_data_address0 = "XXXXXXXXX";
        }
    } else {
        tempData_data_address0 = "XXXXXXXXX";
    }
}

void queue::thread_tempData_data_address1() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            tempData_data_address1 = grp_pop_fu_104_tempData_data_address1.read();
        } else if (ap_sig_bdd_214.read()) {
            tempData_data_address1 = grp_push_fu_87_tempData_data_address1.read();
        } else {
            tempData_data_address1 = "XXXXXXXXX";
        }
    } else {
        tempData_data_address1 = "XXXXXXXXX";
    }
}

void queue::thread_tempData_data_ce0() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            tempData_data_ce0 = grp_pop_fu_104_tempData_data_ce0.read();
        } else if (ap_sig_bdd_214.read()) {
            tempData_data_ce0 = grp_push_fu_87_tempData_data_ce0.read();
        } else {
            tempData_data_ce0 = ap_const_logic_0;
        }
    } else {
        tempData_data_ce0 = ap_const_logic_0;
    }
}

void queue::thread_tempData_data_ce1() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            tempData_data_ce1 = grp_pop_fu_104_tempData_data_ce1.read();
        } else if (ap_sig_bdd_214.read()) {
            tempData_data_ce1 = grp_push_fu_87_tempData_data_ce1.read();
        } else {
            tempData_data_ce1 = ap_const_logic_0;
        }
    } else {
        tempData_data_ce1 = ap_const_logic_0;
    }
}

void queue::thread_tempData_data_d0() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            tempData_data_d0 = grp_pop_fu_104_tempData_data_d0.read();
        } else if (ap_sig_bdd_214.read()) {
            tempData_data_d0 = grp_push_fu_87_tempData_data_d0.read();
        } else {
            tempData_data_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        tempData_data_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void queue::thread_tempData_data_d1() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            tempData_data_d1 = grp_pop_fu_104_tempData_data_d1.read();
        } else if (ap_sig_bdd_214.read()) {
            tempData_data_d1 = grp_push_fu_87_tempData_data_d1.read();
        } else {
            tempData_data_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        tempData_data_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void queue::thread_tempData_data_we0() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            tempData_data_we0 = grp_pop_fu_104_tempData_data_we0.read();
        } else if (ap_sig_bdd_214.read()) {
            tempData_data_we0 = grp_push_fu_87_tempData_data_we0.read();
        } else {
            tempData_data_we0 = ap_const_logic_0;
        }
    } else {
        tempData_data_we0 = ap_const_logic_0;
    }
}

void queue::thread_tempData_data_we1() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            tempData_data_we1 = grp_pop_fu_104_tempData_data_we1.read();
        } else if (ap_sig_bdd_214.read()) {
            tempData_data_we1 = grp_push_fu_87_tempData_data_we1.read();
        } else {
            tempData_data_we1 = ap_const_logic_0;
        }
    } else {
        tempData_data_we1 = ap_const_logic_0;
    }
}

void queue::thread_tempData_priority_address0() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            tempData_priority_address0 = grp_pop_fu_104_tempData_priority_address0.read();
        } else if (ap_sig_bdd_214.read()) {
            tempData_priority_address0 = grp_push_fu_87_tempData_priority_address0.read();
        } else {
            tempData_priority_address0 = "XXXXXXXXX";
        }
    } else {
        tempData_priority_address0 = "XXXXXXXXX";
    }
}

void queue::thread_tempData_priority_address1() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            tempData_priority_address1 = grp_pop_fu_104_tempData_priority_address1.read();
        } else if (ap_sig_bdd_214.read()) {
            tempData_priority_address1 = grp_push_fu_87_tempData_priority_address1.read();
        } else {
            tempData_priority_address1 = "XXXXXXXXX";
        }
    } else {
        tempData_priority_address1 = "XXXXXXXXX";
    }
}

void queue::thread_tempData_priority_ce0() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            tempData_priority_ce0 = grp_pop_fu_104_tempData_priority_ce0.read();
        } else if (ap_sig_bdd_214.read()) {
            tempData_priority_ce0 = grp_push_fu_87_tempData_priority_ce0.read();
        } else {
            tempData_priority_ce0 = ap_const_logic_0;
        }
    } else {
        tempData_priority_ce0 = ap_const_logic_0;
    }
}

void queue::thread_tempData_priority_ce1() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            tempData_priority_ce1 = grp_pop_fu_104_tempData_priority_ce1.read();
        } else if (ap_sig_bdd_214.read()) {
            tempData_priority_ce1 = grp_push_fu_87_tempData_priority_ce1.read();
        } else {
            tempData_priority_ce1 = ap_const_logic_0;
        }
    } else {
        tempData_priority_ce1 = ap_const_logic_0;
    }
}

void queue::thread_tempData_priority_d0() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            tempData_priority_d0 = grp_pop_fu_104_tempData_priority_d0.read();
        } else if (ap_sig_bdd_214.read()) {
            tempData_priority_d0 = grp_push_fu_87_tempData_priority_d0.read();
        } else {
            tempData_priority_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        tempData_priority_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void queue::thread_tempData_priority_d1() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            tempData_priority_d1 = grp_pop_fu_104_tempData_priority_d1.read();
        } else if (ap_sig_bdd_214.read()) {
            tempData_priority_d1 = grp_push_fu_87_tempData_priority_d1.read();
        } else {
            tempData_priority_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        tempData_priority_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void queue::thread_tempData_priority_we0() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            tempData_priority_we0 = grp_pop_fu_104_tempData_priority_we0.read();
        } else if (ap_sig_bdd_214.read()) {
            tempData_priority_we0 = grp_push_fu_87_tempData_priority_we0.read();
        } else {
            tempData_priority_we0 = ap_const_logic_0;
        }
    } else {
        tempData_priority_we0 = ap_const_logic_0;
    }
}

void queue::thread_tempData_priority_we1() {
    if (esl_seteq<1,1,1>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        if (ap_sig_bdd_212.read()) {
            tempData_priority_we1 = grp_pop_fu_104_tempData_priority_we1.read();
        } else if (ap_sig_bdd_214.read()) {
            tempData_priority_we1 = grp_push_fu_87_tempData_priority_we1.read();
        } else {
            tempData_priority_we1 = ap_const_logic_0;
        }
    } else {
        tempData_priority_we1 = ap_const_logic_0;
    }
}

void queue::thread_tmp_fu_137_p2() {
    tmp_fu_137_p2 = (!size.read().is_01() || !ap_const_lv32_C8.is_01())? sc_lv<1>(): sc_lv<1>(size.read() == ap_const_lv32_C8);
}

void queue::thread_tmp_s_fu_131_p2() {
    tmp_s_fu_131_p2 = (!size.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(size.read() == ap_const_lv32_0);
}

void queue::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint()) {
        case 0 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 1 : 
            if (!((esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(tmp_s_reg_211.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_pop_fu_104_ap_done.read())) || (!esl_seteq<1,1,1>(isPush_read_read_fu_48_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_reg_215.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_push_fu_87_ap_done.read())))) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<1>) ("X");
            break;
    }
}
}

