// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="runQueue,hls_ip_2014_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.093000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0}" *)

module runQueue (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        priorityOut_V,
        priorityIn_V,
        cmdOut_V,
        empty,
        full,
        fullOut,
        iterations,
        iterations_ap_vld,
        finished,
        finished_ap_vld,
        currentIteration,
        total,
        ap_return
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 5'b00000;
parameter    ap_ST_st2_fsm_1 = 5'b1;
parameter    ap_ST_st3_fsm_2 = 5'b10;
parameter    ap_ST_st4_fsm_3 = 5'b11;
parameter    ap_ST_st5_fsm_4 = 5'b100;
parameter    ap_ST_st6_fsm_5 = 5'b101;
parameter    ap_ST_st7_fsm_6 = 5'b110;
parameter    ap_ST_st8_fsm_7 = 5'b111;
parameter    ap_ST_st9_fsm_8 = 5'b1000;
parameter    ap_ST_st10_fsm_9 = 5'b1001;
parameter    ap_ST_st11_fsm_10 = 5'b1010;
parameter    ap_ST_st12_fsm_11 = 5'b1011;
parameter    ap_ST_st13_fsm_12 = 5'b1100;
parameter    ap_ST_st14_fsm_13 = 5'b1101;
parameter    ap_ST_st15_fsm_14 = 5'b1110;
parameter    ap_ST_st16_fsm_15 = 5'b1111;
parameter    ap_ST_st17_fsm_16 = 5'b10000;
parameter    ap_ST_st18_fsm_17 = 5'b10001;
parameter    ap_ST_st19_fsm_18 = 5'b10010;
parameter    ap_ST_st20_fsm_19 = 5'b10011;
parameter    ap_ST_st21_fsm_20 = 5'b10100;
parameter    ap_ST_st22_fsm_21 = 5'b10101;
parameter    ap_ST_st23_fsm_22 = 5'b10110;
parameter    ap_ST_st24_fsm_23 = 5'b10111;
parameter    ap_ST_st25_fsm_24 = 5'b11000;
parameter    ap_ST_st26_fsm_25 = 5'b11001;
parameter    ap_ST_st27_fsm_26 = 5'b11010;
parameter    ap_ST_st28_fsm_27 = 5'b11011;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] priorityOut_V;
input  [7:0] priorityIn_V;
output  [1:0] cmdOut_V;
input   empty;
input   full;
output   fullOut;
input  [31:0] iterations;
input   iterations_ap_vld;
output   finished;
output   finished_ap_vld;
output  [31:0] currentIteration;
output  [31:0] total;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] priorityOut_V;
reg[1:0] cmdOut_V;
reg fullOut;
reg finished_ap_vld;
reg[31:0] currentIteration;
reg[31:0] total;
reg   [4:0] ap_CS_fsm = 5'b00000;
reg   [31:0] iterations_in_sig;
reg   [31:0] iterations_preg = 32'b00000000000000000000000000000000;
reg    iterations_ap_vld_in_sig;
reg    iterations_ap_vld_preg = 1'b0;
wire   [7:0] random_priorities_address0;
reg    random_priorities_ce0;
wire   [8:0] random_priorities_q0;
reg    ap_sig_bdd_79;
wire   [31:0] j_1_fu_330_p2;
reg   [31:0] j_1_reg_442;
wire   [31:0] i_fu_336_p2;
reg   [31:0] i_reg_450;
wire   [7:0] tmp_1_fu_342_p1;
reg   [7:0] tmp_1_reg_455;
wire   [0:0] grp_load_fu_309_p1;
wire   [31:0] i_3_fu_357_p2;
reg   [31:0] i_3_reg_463;
wire   [0:0] tmp_4_fu_367_p2;
reg   [0:0] tmp_4_reg_468;
wire   [31:0] result_5_fu_377_p2;
wire   [31:0] i_1_fu_383_p2;
reg   [31:0] i_1_reg_480;
wire   [31:0] result_6_fu_409_p2;
reg   [7:0] priorityIn_V_read_4_reg_501;
reg   [31:0] j_reg_181;
reg   [31:0] result_reg_193;
reg   [31:0] result_3_reg_275;
reg   [31:0] val_assign_reg_205;
reg   [31:0] op2_assign_reg_216;
reg   [31:0] result_1_reg_228;
reg   [31:0] result_2_reg_239;
reg   [31:0] i_2_reg_251;
reg   [7:0] last_reg_263;
reg   [31:0] result_4_reg_287;
wire   [0:0] tmp_2_fu_399_p2;
wire   [63:0] tmp_7_fu_389_p1;
reg   [31:0] count_fu_86;
wire   [31:0] count_1_fu_346_p2;
wire   [0:0] tmp_fu_325_p2;
reg   [0:0] localFull_fu_90;
wire   [0:0] grp_read_fu_119_p2;
wire   [0:0] grp_load_fu_317_p1;
reg   [0:0] localEmpty_fu_94;
wire   [0:0] grp_read_fu_141_p2;
reg   [1:0] cmdOut_V_preg = 2'b00;
reg   [31:0] currentIteration_preg = 32'b00000000000000000000000000000000;
reg   [31:0] total_preg = 32'b00000000000000000000000000000000;
reg   [7:0] priorityOut_V_preg = 8'b00000000;
wire   [7:0] tmp_9_fu_394_p1;
reg    fullOut_preg = 1'b0;
wire   [31:0] tmp_3_fu_363_p1;
wire   [31:0] tmp_5_fu_373_p1;
wire   [31:0] tmp_6_fu_405_p1;
reg   [4:0] ap_NS_fsm;


runQueue_random_priorities #(
    .DataWidth( 9 ),
    .AddressRange( 200 ),
    .AddressWidth( 8 ))
random_priorities_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( random_priorities_address0 ),
    .ce0( random_priorities_ce0 ),
    .q0( random_priorities_q0 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// cmdOut_V_preg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_cmdOut_V_preg
    if (ap_rst == 1'b1) begin
        cmdOut_V_preg <= ap_const_lv2_0;
    end else begin
        if (((ap_ST_st9_fsm_8 == ap_CS_fsm) | ((ap_ST_st10_fsm_9 == ap_CS_fsm) & (ap_const_lv1_0 == grp_load_fu_317_p1)) | ((ap_const_lv1_0 == grp_load_fu_317_p1) & (ap_ST_st22_fsm_21 == ap_CS_fsm)))) begin
            cmdOut_V_preg <= ap_const_lv2_2;
        end else if ((((ap_ST_st4_fsm_3 == ap_CS_fsm) & (grp_load_fu_309_p1 == ap_const_lv1_0)) | (ap_ST_st3_fsm_2 == ap_CS_fsm) | (ap_ST_st15_fsm_14 == ap_CS_fsm) | ((grp_load_fu_309_p1 == ap_const_lv1_0) & (ap_ST_st16_fsm_15 == ap_CS_fsm)))) begin
            cmdOut_V_preg <= ap_const_lv2_1;
        end else if ((((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_79) | ((ap_ST_st16_fsm_15 == ap_CS_fsm) & ~(grp_load_fu_309_p1 == ap_const_lv1_0)) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_fu_325_p2)) | ((ap_ST_st10_fsm_9 == ap_CS_fsm) & ~(ap_const_lv1_0 == grp_load_fu_317_p1)) | ((ap_ST_st4_fsm_3 == ap_CS_fsm) & ~(grp_load_fu_309_p1 == ap_const_lv1_0)) | (ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st20_fsm_19 == ap_CS_fsm) | (~(ap_const_lv1_0 == grp_load_fu_317_p1) & (ap_ST_st22_fsm_21 == ap_CS_fsm)) | (ap_ST_st26_fsm_25 == ap_CS_fsm))) begin
            cmdOut_V_preg <= ap_const_lv2_0;
        end
    end
end

/// currentIteration_preg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_currentIteration_preg
    if (ap_rst == 1'b1) begin
        currentIteration_preg <= ap_const_lv32_0;
    end else begin
        if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_fu_325_p2))) begin
            currentIteration_preg <= j_reg_181;
        end
    end
end

/// fullOut_preg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_fullOut_preg
    if (ap_rst == 1'b1) begin
        fullOut_preg <= ap_const_logic_0;
    end else begin
        if ((ap_ST_st5_fsm_4 == ap_CS_fsm)) begin
            fullOut_preg <= grp_read_fu_119_p2;
        end
    end
end

/// iterations_ap_vld_preg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_iterations_ap_vld_preg
    if (ap_rst == 1'b1) begin
        iterations_ap_vld_preg <= ap_const_logic_0;
    end else begin
        if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_fu_325_p2))) begin
            iterations_ap_vld_preg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == iterations_ap_vld) & ~((ap_ST_st1_fsm_0 == ap_CS_fsm) & (ap_const_logic_0 == ap_start)))) begin
            iterations_ap_vld_preg <= iterations_ap_vld;
        end
    end
end

/// iterations_preg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_iterations_preg
    if (ap_rst == 1'b1) begin
        iterations_preg <= ap_const_lv32_0;
    end else begin
        if (((ap_const_logic_1 == iterations_ap_vld) & ~((ap_ST_st1_fsm_0 == ap_CS_fsm) & (ap_const_logic_0 == ap_start)))) begin
            iterations_preg <= iterations;
        end
    end
end

/// priorityOut_V_preg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_priorityOut_V_preg
    if (ap_rst == 1'b1) begin
        priorityOut_V_preg <= ap_const_lv8_0;
    end else begin
        if ((ap_ST_st18_fsm_17 == ap_CS_fsm)) begin
            priorityOut_V_preg <= tmp_9_fu_394_p1;
        end else if ((ap_ST_st5_fsm_4 == ap_CS_fsm)) begin
            priorityOut_V_preg <= tmp_1_reg_455;
        end
    end
end

/// total_preg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_total_preg
    if (ap_rst == 1'b1) begin
        total_preg <= ap_const_lv32_0;
    end else begin
        if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_fu_325_p2))) begin
            total_preg <= count_fu_86;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st8_fsm_7 == ap_CS_fsm)) begin
        count_fu_86 <= count_1_fu_346_p2;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_79)) begin
        count_fu_86 <= ap_const_lv32_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st21_fsm_20 == ap_CS_fsm)) begin
        i_2_reg_251 <= i_1_reg_480;
    end else if ((ap_ST_st15_fsm_14 == ap_CS_fsm)) begin
        i_2_reg_251 <= ap_const_lv32_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st28_fsm_27 == ap_CS_fsm)) begin
        j_reg_181 <= j_1_reg_442;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_79)) begin
        j_reg_181 <= ap_const_lv32_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st27_fsm_26 == ap_CS_fsm)) begin
        last_reg_263 <= priorityIn_V_read_4_reg_501;
    end else if (((ap_ST_st16_fsm_15 == ap_CS_fsm) & ~(grp_load_fu_309_p1 == ap_const_lv1_0))) begin
        last_reg_263 <= ap_const_lv8_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st14_fsm_13 == ap_CS_fsm)) begin
        op2_assign_reg_216 <= i_3_reg_463;
    end else if ((ap_ST_st9_fsm_8 == ap_CS_fsm)) begin
        op2_assign_reg_216 <= ap_const_lv32_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st14_fsm_13 == ap_CS_fsm)) begin
        result_1_reg_228 <= result_2_reg_239;
    end else if ((ap_ST_st9_fsm_8 == ap_CS_fsm)) begin
        result_1_reg_228 <= result_reg_193;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st11_fsm_10 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_4_fu_367_p2))) begin
        result_2_reg_239 <= result_1_reg_228;
    end else if (((ap_ST_st12_fsm_11 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_4_reg_468))) begin
        result_2_reg_239 <= result_5_fu_377_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st27_fsm_26 == ap_CS_fsm)) begin
        result_3_reg_275 <= result_4_reg_287;
    end else if (((ap_ST_st16_fsm_15 == ap_CS_fsm) & ~(grp_load_fu_309_p1 == ap_const_lv1_0))) begin
        result_3_reg_275 <= result_1_reg_228;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st23_fsm_22 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_2_fu_399_p2))) begin
        result_4_reg_287 <= result_3_reg_275;
    end else if ((ap_ST_st24_fsm_23 == ap_CS_fsm)) begin
        result_4_reg_287 <= result_6_fu_409_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st28_fsm_27 == ap_CS_fsm)) begin
        result_reg_193 <= result_3_reg_275;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_79)) begin
        result_reg_193 <= ap_const_lv32_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st8_fsm_7 == ap_CS_fsm)) begin
        val_assign_reg_205 <= i_reg_450;
    end else if ((ap_ST_st3_fsm_2 == ap_CS_fsm)) begin
        val_assign_reg_205 <= ap_const_lv32_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st16_fsm_15 == ap_CS_fsm)) begin
        i_1_reg_480 <= i_1_fu_383_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st10_fsm_9 == ap_CS_fsm)) begin
        i_3_reg_463 <= i_3_fu_357_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        i_reg_450 <= i_fu_336_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        j_1_reg_442 <= j_1_fu_330_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st12_fsm_11 == ap_CS_fsm) | (ap_ST_st25_fsm_24 == ap_CS_fsm) | ((ap_ST_st16_fsm_15 == ap_CS_fsm) & ~(grp_load_fu_309_p1 == ap_const_lv1_0)) | ((ap_ST_st4_fsm_3 == ap_CS_fsm) & ~(grp_load_fu_309_p1 == ap_const_lv1_0)))) begin
        localEmpty_fu_94 <= grp_read_fu_141_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_fu_325_p2)) | (ap_ST_st6_fsm_5 == ap_CS_fsm) | ((ap_ST_st10_fsm_9 == ap_CS_fsm) & ~(ap_const_lv1_0 == grp_load_fu_317_p1)) | (ap_ST_st19_fsm_18 == ap_CS_fsm))) begin
        localFull_fu_90 <= grp_read_fu_119_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st25_fsm_24 == ap_CS_fsm)) begin
        priorityIn_V_read_4_reg_501 <= priorityIn_V;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & (grp_load_fu_309_p1 == ap_const_lv1_0))) begin
        tmp_1_reg_455 <= tmp_1_fu_342_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st11_fsm_10 == ap_CS_fsm)) begin
        tmp_4_reg_468 <= tmp_4_fu_367_p2;
    end
end

/// ap_done assign process. ///
always @ (ap_CS_fsm or tmp_fu_325_p2)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_fu_325_p2))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or tmp_fu_325_p2)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_fu_325_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// cmdOut_V assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_79 or grp_load_fu_309_p1 or tmp_fu_325_p2 or grp_load_fu_317_p1 or cmdOut_V_preg)
begin
    if (((ap_ST_st9_fsm_8 == ap_CS_fsm) | ((ap_ST_st10_fsm_9 == ap_CS_fsm) & (ap_const_lv1_0 == grp_load_fu_317_p1)) | ((ap_const_lv1_0 == grp_load_fu_317_p1) & (ap_ST_st22_fsm_21 == ap_CS_fsm)))) begin
        cmdOut_V = ap_const_lv2_2;
    end else if ((((ap_ST_st4_fsm_3 == ap_CS_fsm) & (grp_load_fu_309_p1 == ap_const_lv1_0)) | (ap_ST_st3_fsm_2 == ap_CS_fsm) | (ap_ST_st15_fsm_14 == ap_CS_fsm) | ((grp_load_fu_309_p1 == ap_const_lv1_0) & (ap_ST_st16_fsm_15 == ap_CS_fsm)))) begin
        cmdOut_V = ap_const_lv2_1;
    end else if ((((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_79) | ((ap_ST_st16_fsm_15 == ap_CS_fsm) & ~(grp_load_fu_309_p1 == ap_const_lv1_0)) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_fu_325_p2)) | ((ap_ST_st10_fsm_9 == ap_CS_fsm) & ~(ap_const_lv1_0 == grp_load_fu_317_p1)) | ((ap_ST_st4_fsm_3 == ap_CS_fsm) & ~(grp_load_fu_309_p1 == ap_const_lv1_0)) | (ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st20_fsm_19 == ap_CS_fsm) | (~(ap_const_lv1_0 == grp_load_fu_317_p1) & (ap_ST_st22_fsm_21 == ap_CS_fsm)) | (ap_ST_st26_fsm_25 == ap_CS_fsm))) begin
        cmdOut_V = ap_const_lv2_0;
    end else begin
        cmdOut_V = cmdOut_V_preg;
    end
end

/// currentIteration assign process. ///
always @ (ap_CS_fsm or j_reg_181 or tmp_fu_325_p2 or currentIteration_preg)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_fu_325_p2))) begin
        currentIteration = j_reg_181;
    end else begin
        currentIteration = currentIteration_preg;
    end
end

/// finished_ap_vld assign process. ///
always @ (ap_CS_fsm or tmp_fu_325_p2)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_fu_325_p2))) begin
        finished_ap_vld = ap_const_logic_1;
    end else begin
        finished_ap_vld = ap_const_logic_0;
    end
end

/// fullOut assign process. ///
always @ (ap_CS_fsm or full or fullOut_preg)
begin
    if ((ap_ST_st5_fsm_4 == ap_CS_fsm)) begin
        fullOut = full;
    end else begin
        fullOut = fullOut_preg;
    end
end

/// iterations_ap_vld_in_sig assign process. ///
always @ (iterations_ap_vld or iterations_ap_vld_preg)
begin
    if ((ap_const_logic_1 == iterations_ap_vld)) begin
        iterations_ap_vld_in_sig = iterations_ap_vld;
    end else begin
        iterations_ap_vld_in_sig = iterations_ap_vld_preg;
    end
end

/// iterations_in_sig assign process. ///
always @ (iterations or iterations_preg or iterations_ap_vld)
begin
    if ((ap_const_logic_1 == iterations_ap_vld)) begin
        iterations_in_sig = iterations;
    end else begin
        iterations_in_sig = iterations_preg;
    end
end

/// priorityOut_V assign process. ///
always @ (ap_CS_fsm or tmp_1_reg_455 or priorityOut_V_preg or tmp_9_fu_394_p1)
begin
    if ((ap_ST_st18_fsm_17 == ap_CS_fsm)) begin
        priorityOut_V = tmp_9_fu_394_p1;
    end else if ((ap_ST_st5_fsm_4 == ap_CS_fsm)) begin
        priorityOut_V = tmp_1_reg_455;
    end else begin
        priorityOut_V = priorityOut_V_preg;
    end
end

/// random_priorities_ce0 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st17_fsm_16 == ap_CS_fsm)) begin
        random_priorities_ce0 = ap_const_logic_1;
    end else begin
        random_priorities_ce0 = ap_const_logic_0;
    end
end

/// total assign process. ///
always @ (ap_CS_fsm or count_fu_86 or tmp_fu_325_p2 or total_preg)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_fu_325_p2))) begin
        total = count_fu_86;
    end else begin
        total = total_preg;
    end
end
always @ (ap_CS_fsm or ap_sig_bdd_79 or grp_load_fu_309_p1 or tmp_2_fu_399_p2 or tmp_fu_325_p2 or grp_load_fu_317_p1)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~ap_sig_bdd_79) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            if ((ap_const_lv1_0 == tmp_fu_325_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        ap_ST_st3_fsm_2 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
        ap_ST_st4_fsm_3 : 
            if (~(grp_load_fu_309_p1 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        ap_ST_st5_fsm_4 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
        ap_ST_st6_fsm_5 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
        ap_ST_st7_fsm_6 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
        ap_ST_st8_fsm_7 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
        ap_ST_st9_fsm_8 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
        ap_ST_st10_fsm_9 : 
            if (~(ap_const_lv1_0 == grp_load_fu_317_p1)) begin
                ap_NS_fsm = ap_ST_st15_fsm_14;
            end else begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end
        ap_ST_st11_fsm_10 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
        ap_ST_st12_fsm_11 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
        ap_ST_st13_fsm_12 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
        ap_ST_st14_fsm_13 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
        ap_ST_st15_fsm_14 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
        ap_ST_st16_fsm_15 : 
            if (~(grp_load_fu_309_p1 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st22_fsm_21;
            end else begin
                ap_NS_fsm = ap_ST_st17_fsm_16;
            end
        ap_ST_st17_fsm_16 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
        ap_ST_st18_fsm_17 : 
            ap_NS_fsm = ap_ST_st19_fsm_18;
        ap_ST_st19_fsm_18 : 
            ap_NS_fsm = ap_ST_st20_fsm_19;
        ap_ST_st20_fsm_19 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
        ap_ST_st21_fsm_20 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
        ap_ST_st22_fsm_21 : 
            if (~(ap_const_lv1_0 == grp_load_fu_317_p1)) begin
                ap_NS_fsm = ap_ST_st28_fsm_27;
            end else begin
                ap_NS_fsm = ap_ST_st23_fsm_22;
            end
        ap_ST_st23_fsm_22 : 
            if ((ap_const_lv1_0 == tmp_2_fu_399_p2)) begin
                ap_NS_fsm = ap_ST_st25_fsm_24;
            end else begin
                ap_NS_fsm = ap_ST_st24_fsm_23;
            end
        ap_ST_st24_fsm_23 : 
            ap_NS_fsm = ap_ST_st25_fsm_24;
        ap_ST_st25_fsm_24 : 
            ap_NS_fsm = ap_ST_st26_fsm_25;
        ap_ST_st26_fsm_25 : 
            ap_NS_fsm = ap_ST_st27_fsm_26;
        ap_ST_st27_fsm_26 : 
            ap_NS_fsm = ap_ST_st22_fsm_21;
        ap_ST_st28_fsm_27 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
        default : 
            ap_NS_fsm = 'bx;
    endcase
end
assign ap_return = result_reg_193;

/// ap_sig_bdd_79 assign process. ///
always @ (ap_start or iterations_ap_vld_in_sig)
begin
    ap_sig_bdd_79 = ((iterations_ap_vld_in_sig == ap_const_logic_0) | (ap_start == ap_const_logic_0));
end
assign count_1_fu_346_p2 = (count_fu_86 + ap_const_lv32_1);
assign finished = ap_const_lv1_1;
assign grp_load_fu_309_p1 = localFull_fu_90;
assign grp_load_fu_317_p1 = localEmpty_fu_94;
assign grp_read_fu_119_p2 = full;
assign grp_read_fu_141_p2 = empty;
assign i_1_fu_383_p2 = (i_2_reg_251 + ap_const_lv32_1);
assign i_3_fu_357_p2 = (op2_assign_reg_216 + ap_const_lv32_1);
assign i_fu_336_p2 = (val_assign_reg_205 + ap_const_lv32_1);
assign j_1_fu_330_p2 = (j_reg_181 + ap_const_lv32_1);
assign random_priorities_address0 = tmp_7_fu_389_p1;
assign result_5_fu_377_p2 = (result_1_reg_228 + tmp_5_fu_373_p1);
assign result_6_fu_409_p2 = (result_3_reg_275 + tmp_6_fu_405_p1);
assign tmp_1_fu_342_p1 = val_assign_reg_205[7:0];
assign tmp_2_fu_399_p2 = (last_reg_263 > priorityIn_V? 1'b1: 1'b0);
assign tmp_3_fu_363_p1 = $unsigned(priorityIn_V);
assign tmp_4_fu_367_p2 = (tmp_3_fu_363_p1 == op2_assign_reg_216? 1'b1: 1'b0);
assign tmp_5_fu_373_p1 = $unsigned(priorityIn_V);
assign tmp_6_fu_405_p1 = $unsigned(priorityIn_V);
assign tmp_7_fu_389_p1 = $unsigned(i_2_reg_251);
assign tmp_9_fu_394_p1 = random_priorities_q0[7:0];
assign tmp_fu_325_p2 = ($signed(j_reg_181) < $signed(iterations_in_sig)? 1'b1: 1'b0);


endmodule //runQueue

