// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module runTest (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_return
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 4'b0000;
parameter    ap_ST_st2_fsm_1 = 4'b1;
parameter    ap_ST_st3_fsm_2 = 4'b10;
parameter    ap_ST_st4_fsm_3 = 4'b11;
parameter    ap_ST_st5_fsm_4 = 4'b100;
parameter    ap_ST_st6_fsm_5 = 4'b101;
parameter    ap_ST_st7_fsm_6 = 4'b110;
parameter    ap_ST_st8_fsm_7 = 4'b111;
parameter    ap_ST_st9_fsm_8 = 4'b1000;
parameter    ap_ST_st10_fsm_9 = 4'b1001;
parameter    ap_ST_st11_fsm_10 = 4'b1010;
parameter    ap_ST_st12_fsm_11 = 4'b1011;
parameter    ap_ST_st13_fsm_12 = 4'b1100;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv32_FFFFFFFF = 32'b11111111111111111111111111111111;
parameter    ap_const_lv8_C8 = 8'b11001000;
parameter    ap_const_lv8_1 = 8'b1;
parameter    ap_const_lv8_C7 = 8'b11000111;
parameter    ap_const_lv32_C8 = 32'b11001000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [0:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[0:0] ap_return;
reg   [3:0] ap_CS_fsm = 4'b0000;
wire   [7:0] random_priorities_address0;
reg    random_priorities_ce0;
wire   [8:0] random_priorities_q0;
wire   [7:0] i_fu_202_p2;
reg   [7:0] i_reg_369;
wire   [7:0] current_data_fu_208_p2;
reg   [7:0] current_data_reg_374;
wire   [0:0] exitcond4_fu_196_p2;
wire   [8:0] current_priority_cast6_cast_fu_215_p1;
reg   [8:0] current_priority_cast6_cast_reg_379;
wire   [31:0] i_1_cast5_fu_220_p1;
reg   [31:0] i_1_cast5_reg_384;
wire   [7:0] i_6_fu_230_p2;
reg   [7:0] i_6_reg_392;
wire   [0:0] result_s_fu_263_p2;
wire    grp_queue_fu_170_ap_done;
wire   [7:0] i_5_fu_275_p2;
reg   [7:0] i_5_reg_405;
wire   [0:0] exitcond2_fu_269_p2;
wire   [7:0] current_data_1_fu_286_p2;
reg   [7:0] current_data_1_reg_415;
reg   [8:0] current_priority_1_reg_420;
wire   [7:0] i_7_fu_299_p2;
wire   [7:0] i_8_fu_316_p2;
reg   [7:0] i_8_reg_436;
reg   [31:0] out_priority_2_reg_441;
reg   [31:0] out_data_1_reg_446;
wire   [0:0] slt_fu_322_p2;
reg   [0:0] slt_reg_452;
reg   [7:0] dequeuedItems_addr_1_reg_457;
wire   [0:0] tmp_7_fu_355_p2;
reg   [0:0] tmp_7_reg_462;
wire   [0:0] result_4_fu_361_p2;
reg   [7:0] dequeuedItems_address0;
reg    dequeuedItems_ce0;
reg    dequeuedItems_we0;
reg   [31:0] dequeuedItems_d0;
wire   [31:0] dequeuedItems_q0;
wire    grp_queue_fu_170_ap_start;
wire    grp_queue_fu_170_ap_idle;
wire    grp_queue_fu_170_ap_ready;
reg    grp_queue_fu_170_isPush;
reg   [8:0] grp_queue_fu_170_inData_priority;
reg   [7:0] grp_queue_fu_170_inData_data;
wire   [31:0] grp_queue_fu_170_ap_return_0;
wire   [31:0] grp_queue_fu_170_ap_return_1;
reg   [7:0] current_priority_reg_77;
reg   [0:0] result_reg_88;
reg   [7:0] i_1_reg_100;
reg   [7:0] i_2_reg_112;
wire   [0:0] exitcond3_fu_224_p2;
reg   [7:0] i_3_reg_124;
wire   [0:0] exitcond1_fu_293_p2;
reg   [31:0] last_reg_135;
reg   [0:0] result_2_reg_147;
reg   [7:0] i_4_reg_158;
reg    grp_queue_fu_170_ap_start_ap_start_reg = 1'b0;
wire   [0:0] exitcond_fu_310_p2;
wire   [63:0] tmp_6_fu_281_p1;
wire   [63:0] tmp_9_fu_305_p1;
wire   [63:0] tmp_1_fu_328_p1;
wire   [7:0] tmp_3_fu_241_p2;
wire   [31:0] tmp_3_cast_fu_247_p1;
wire   [0:0] tmp_4_fu_251_p2;
wire   [0:0] tmp_fu_236_p2;
wire   [0:0] tmp_2_fu_257_p2;
wire   [0:0] notlhs_fu_338_p2;
wire   [0:0] notrhs_fu_343_p2;
wire   [0:0] tmp2_fu_349_p2;
wire   [0:0] rev1_fu_333_p2;
reg   [0:0] ap_return_preg = 1'b0;
reg   [3:0] ap_NS_fsm;


runTest_random_priorities #(
    .DataWidth( 9 ),
    .AddressRange( 200 ),
    .AddressWidth( 8 ))
random_priorities_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( random_priorities_address0 ),
    .ce0( random_priorities_ce0 ),
    .q0( random_priorities_q0 )
);

runTest_dequeuedItems #(
    .DataWidth( 32 ),
    .AddressRange( 200 ),
    .AddressWidth( 8 ))
dequeuedItems_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( dequeuedItems_address0 ),
    .ce0( dequeuedItems_ce0 ),
    .we0( dequeuedItems_we0 ),
    .d0( dequeuedItems_d0 ),
    .q0( dequeuedItems_q0 )
);

queue grp_queue_fu_170(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_queue_fu_170_ap_start ),
    .ap_done( grp_queue_fu_170_ap_done ),
    .ap_idle( grp_queue_fu_170_ap_idle ),
    .ap_ready( grp_queue_fu_170_ap_ready ),
    .isPush( grp_queue_fu_170_isPush ),
    .inData_priority( grp_queue_fu_170_inData_priority ),
    .inData_data( grp_queue_fu_170_inData_data ),
    .ap_return_0( grp_queue_fu_170_ap_return_0 ),
    .ap_return_1( grp_queue_fu_170_ap_return_1 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_return_preg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_return_preg
    if (ap_rst == 1'b1) begin
        ap_return_preg <= ap_const_lv1_0;
    end else begin
        if (((ap_ST_st10_fsm_9 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_310_p2))) begin
            ap_return_preg <= result_2_reg_147;
        end
    end
end

/// grp_queue_fu_170_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_queue_fu_170_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_queue_fu_170_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if ((((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond4_fu_196_p2 == ap_const_lv1_0)) | (ap_ST_st7_fsm_6 == ap_CS_fsm) | ((ap_ST_st4_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_224_p2)) | ((ap_ST_st10_fsm_9 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_fu_310_p2)))) begin
            grp_queue_fu_170_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_queue_fu_170_ap_ready)) begin
            grp_queue_fu_170_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_logic_0 == grp_queue_fu_170_ap_done) & (ap_ST_st3_fsm_2 == ap_CS_fsm))) begin
        current_priority_reg_77 <= i_reg_369;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0))) begin
        current_priority_reg_77 <= ap_const_lv8_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(exitcond4_fu_196_p2 == ap_const_lv1_0))) begin
        i_1_reg_100 <= ap_const_lv8_0;
    end else if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_queue_fu_170_ap_done))) begin
        i_1_reg_100 <= i_6_reg_392;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond3_fu_224_p2))) begin
        i_2_reg_112 <= ap_const_lv8_0;
    end else if ((~(ap_const_logic_0 == grp_queue_fu_170_ap_done) & (ap_ST_st8_fsm_7 == ap_CS_fsm))) begin
        i_2_reg_112 <= i_5_reg_405;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st6_fsm_5 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond2_fu_269_p2))) begin
        i_3_reg_124 <= ap_const_lv8_0;
    end else if (((ap_ST_st9_fsm_8 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_293_p2))) begin
        i_3_reg_124 <= i_7_fu_299_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st9_fsm_8 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond1_fu_293_p2))) begin
        i_4_reg_158 <= ap_const_lv8_0;
    end else if ((ap_ST_st13_fsm_12 == ap_CS_fsm)) begin
        i_4_reg_158 <= i_8_reg_436;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st9_fsm_8 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond1_fu_293_p2))) begin
        last_reg_135 <= ap_const_lv32_0;
    end else if ((ap_ST_st13_fsm_12 == ap_CS_fsm)) begin
        last_reg_135 <= out_priority_2_reg_441;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st9_fsm_8 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond1_fu_293_p2))) begin
        result_2_reg_147 <= result_reg_88;
    end else if ((ap_ST_st13_fsm_12 == ap_CS_fsm)) begin
        result_2_reg_147 <= result_4_fu_361_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(exitcond4_fu_196_p2 == ap_const_lv1_0))) begin
        result_reg_88 <= ap_const_lv1_1;
    end else if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_queue_fu_170_ap_done))) begin
        result_reg_88 <= result_s_fu_263_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st7_fsm_6 == ap_CS_fsm)) begin
        current_data_1_reg_415 <= current_data_1_fu_286_p2;
        current_priority_1_reg_420 <= random_priorities_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond4_fu_196_p2 == ap_const_lv1_0))) begin
        current_data_reg_374 <= current_data_fu_208_p2;
        current_priority_cast6_cast_reg_379[0] <= current_priority_cast6_cast_fu_215_p1[0];
current_priority_cast6_cast_reg_379[1] <= current_priority_cast6_cast_fu_215_p1[1];
current_priority_cast6_cast_reg_379[2] <= current_priority_cast6_cast_fu_215_p1[2];
current_priority_cast6_cast_reg_379[3] <= current_priority_cast6_cast_fu_215_p1[3];
current_priority_cast6_cast_reg_379[4] <= current_priority_cast6_cast_fu_215_p1[4];
current_priority_cast6_cast_reg_379[5] <= current_priority_cast6_cast_fu_215_p1[5];
current_priority_cast6_cast_reg_379[6] <= current_priority_cast6_cast_fu_215_p1[6];
current_priority_cast6_cast_reg_379[7] <= current_priority_cast6_cast_fu_215_p1[7];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_logic_0 == grp_queue_fu_170_ap_done) & (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        dequeuedItems_addr_1_reg_457 <= tmp_1_fu_328_p1;
        out_data_1_reg_446 <= grp_queue_fu_170_ap_return_1;
        out_priority_2_reg_441 <= grp_queue_fu_170_ap_return_0;
        slt_reg_452 <= slt_fu_322_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        i_1_cast5_reg_384[0] <= i_1_cast5_fu_220_p1[0];
i_1_cast5_reg_384[1] <= i_1_cast5_fu_220_p1[1];
i_1_cast5_reg_384[2] <= i_1_cast5_fu_220_p1[2];
i_1_cast5_reg_384[3] <= i_1_cast5_fu_220_p1[3];
i_1_cast5_reg_384[4] <= i_1_cast5_fu_220_p1[4];
i_1_cast5_reg_384[5] <= i_1_cast5_fu_220_p1[5];
i_1_cast5_reg_384[6] <= i_1_cast5_fu_220_p1[6];
i_1_cast5_reg_384[7] <= i_1_cast5_fu_220_p1[7];
        i_6_reg_392 <= i_6_fu_230_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        i_5_reg_405 <= i_5_fu_275_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st10_fsm_9 == ap_CS_fsm)) begin
        i_8_reg_436 <= i_8_fu_316_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        i_reg_369 <= i_fu_202_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st12_fsm_11 == ap_CS_fsm)) begin
        tmp_7_reg_462 <= tmp_7_fu_355_p2;
    end
end

/// ap_done assign process. ///
always @ (ap_start or ap_CS_fsm or exitcond_fu_310_p2)
begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm)) | ((ap_ST_st10_fsm_9 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_310_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or exitcond_fu_310_p2)
begin
    if (((ap_ST_st10_fsm_9 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_310_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_return assign process. ///
always @ (ap_CS_fsm or result_2_reg_147 or exitcond_fu_310_p2 or ap_return_preg)
begin
    if (((ap_ST_st10_fsm_9 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_310_p2))) begin
        ap_return = result_2_reg_147;
    end else begin
        ap_return = ap_return_preg;
    end
end

/// dequeuedItems_address0 assign process. ///
always @ (ap_CS_fsm or dequeuedItems_addr_1_reg_457 or tmp_9_fu_305_p1 or tmp_1_fu_328_p1)
begin
    if ((ap_ST_st12_fsm_11 == ap_CS_fsm)) begin
        dequeuedItems_address0 = dequeuedItems_addr_1_reg_457;
    end else if ((ap_ST_st9_fsm_8 == ap_CS_fsm)) begin
        dequeuedItems_address0 = tmp_9_fu_305_p1;
    end else if ((ap_ST_st11_fsm_10 == ap_CS_fsm)) begin
        dequeuedItems_address0 = tmp_1_fu_328_p1;
    end else begin
        dequeuedItems_address0 = 'bx;
    end
end

/// dequeuedItems_ce0 assign process. ///
always @ (ap_CS_fsm or grp_queue_fu_170_ap_done)
begin
    if (((ap_ST_st9_fsm_8 == ap_CS_fsm) | (~(ap_const_logic_0 == grp_queue_fu_170_ap_done) & (ap_ST_st11_fsm_10 == ap_CS_fsm)) | (ap_ST_st12_fsm_11 == ap_CS_fsm))) begin
        dequeuedItems_ce0 = ap_const_logic_1;
    end else begin
        dequeuedItems_ce0 = ap_const_logic_0;
    end
end

/// dequeuedItems_d0 assign process. ///
always @ (ap_CS_fsm or out_data_1_reg_446)
begin
    if ((ap_ST_st12_fsm_11 == ap_CS_fsm)) begin
        dequeuedItems_d0 = out_data_1_reg_446;
    end else if ((ap_ST_st9_fsm_8 == ap_CS_fsm)) begin
        dequeuedItems_d0 = ap_const_lv32_FFFFFFFF;
    end else begin
        dequeuedItems_d0 = 'bx;
    end
end

/// dequeuedItems_we0 assign process. ///
always @ (ap_CS_fsm or exitcond1_fu_293_p2)
begin
    if (((ap_ST_st12_fsm_11 == ap_CS_fsm) | ((ap_ST_st9_fsm_8 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_293_p2)))) begin
        dequeuedItems_we0 = ap_const_logic_1;
    end else begin
        dequeuedItems_we0 = ap_const_logic_0;
    end
end

/// grp_queue_fu_170_inData_data assign process. ///
always @ (ap_CS_fsm or current_data_reg_374 or current_data_1_reg_415)
begin
    if ((ap_ST_st8_fsm_7 == ap_CS_fsm)) begin
        grp_queue_fu_170_inData_data = current_data_1_reg_415;
    end else if (((ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        grp_queue_fu_170_inData_data = ap_const_lv8_0;
    end else if ((ap_ST_st3_fsm_2 == ap_CS_fsm)) begin
        grp_queue_fu_170_inData_data = current_data_reg_374;
    end else begin
        grp_queue_fu_170_inData_data = 'bx;
    end
end

/// grp_queue_fu_170_inData_priority assign process. ///
always @ (ap_CS_fsm or current_priority_cast6_cast_reg_379 or current_priority_1_reg_420)
begin
    if ((ap_ST_st8_fsm_7 == ap_CS_fsm)) begin
        grp_queue_fu_170_inData_priority = current_priority_1_reg_420;
    end else if (((ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        grp_queue_fu_170_inData_priority = ap_const_lv9_0;
    end else if ((ap_ST_st3_fsm_2 == ap_CS_fsm)) begin
        grp_queue_fu_170_inData_priority = current_priority_cast6_cast_reg_379;
    end else begin
        grp_queue_fu_170_inData_priority = 'bx;
    end
end

/// grp_queue_fu_170_isPush assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        grp_queue_fu_170_isPush = ap_const_lv1_0;
    end else if (((ap_ST_st3_fsm_2 == ap_CS_fsm) | (ap_ST_st8_fsm_7 == ap_CS_fsm))) begin
        grp_queue_fu_170_isPush = ap_const_lv1_1;
    end else begin
        grp_queue_fu_170_isPush = 'bx;
    end
end

/// random_priorities_ce0 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        random_priorities_ce0 = ap_const_logic_1;
    end else begin
        random_priorities_ce0 = ap_const_logic_0;
    end
end
always @ (ap_start or ap_CS_fsm or exitcond4_fu_196_p2 or grp_queue_fu_170_ap_done or exitcond2_fu_269_p2 or exitcond3_fu_224_p2 or exitcond1_fu_293_p2 or exitcond_fu_310_p2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            if (~(exitcond4_fu_196_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        ap_ST_st3_fsm_2 : 
            if (~(ap_const_logic_0 == grp_queue_fu_170_ap_done)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        ap_ST_st4_fsm_3 : 
            if (~(ap_const_lv1_0 == exitcond3_fu_224_p2)) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        ap_ST_st5_fsm_4 : 
            if (~(ap_const_logic_0 == grp_queue_fu_170_ap_done)) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        ap_ST_st6_fsm_5 : 
            if (~(ap_const_lv1_0 == exitcond2_fu_269_p2)) begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        ap_ST_st7_fsm_6 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
        ap_ST_st8_fsm_7 : 
            if (~(ap_const_logic_0 == grp_queue_fu_170_ap_done)) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end
        ap_ST_st9_fsm_8 : 
            if ((ap_const_lv1_0 == exitcond1_fu_293_p2)) begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end else begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end
        ap_ST_st10_fsm_9 : 
            if (~(ap_const_lv1_0 == exitcond_fu_310_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end
        ap_ST_st11_fsm_10 : 
            if (~(ap_const_logic_0 == grp_queue_fu_170_ap_done)) begin
                ap_NS_fsm = ap_ST_st12_fsm_11;
            end else begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end
        ap_ST_st12_fsm_11 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
        ap_ST_st13_fsm_12 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
        default : 
            ap_NS_fsm = 'bx;
    endcase
end
assign current_data_1_fu_286_p2 = (ap_const_lv8_C7 - i_2_reg_112);
assign current_data_fu_208_p2 = (ap_const_lv8_C7 - current_priority_reg_77);
assign current_priority_cast6_cast_fu_215_p1 = $unsigned(current_priority_reg_77);
assign exitcond1_fu_293_p2 = (i_3_reg_124 == ap_const_lv8_C8? 1'b1: 1'b0);
assign exitcond2_fu_269_p2 = (i_2_reg_112 == ap_const_lv8_C8? 1'b1: 1'b0);
assign exitcond3_fu_224_p2 = (i_1_reg_100 == ap_const_lv8_C8? 1'b1: 1'b0);
assign exitcond4_fu_196_p2 = (current_priority_reg_77 == ap_const_lv8_C8? 1'b1: 1'b0);
assign exitcond_fu_310_p2 = (i_4_reg_158 == ap_const_lv8_C8? 1'b1: 1'b0);
assign grp_queue_fu_170_ap_start = grp_queue_fu_170_ap_start_ap_start_reg;
assign i_1_cast5_fu_220_p1 = $unsigned(i_1_reg_100);
assign i_5_fu_275_p2 = (i_2_reg_112 + ap_const_lv8_1);
assign i_6_fu_230_p2 = (i_1_reg_100 + ap_const_lv8_1);
assign i_7_fu_299_p2 = (i_3_reg_124 + ap_const_lv8_1);
assign i_8_fu_316_p2 = (i_4_reg_158 + ap_const_lv8_1);
assign i_fu_202_p2 = (current_priority_reg_77 + ap_const_lv8_1);
assign notlhs_fu_338_p2 = ($signed(out_data_1_reg_446) < $signed(32'b11001000)? 1'b1: 1'b0);
assign notrhs_fu_343_p2 = ($signed(dequeuedItems_q0) < $signed(32'b1)? 1'b1: 1'b0);
assign random_priorities_address0 = tmp_6_fu_281_p1;
assign result_4_fu_361_p2 = (result_2_reg_147 & tmp_7_reg_462);
assign result_s_fu_263_p2 = (result_reg_88 & tmp_2_fu_257_p2);
assign rev1_fu_333_p2 = (slt_reg_452 ^ ap_const_lv1_1);
assign slt_fu_322_p2 = ($signed(grp_queue_fu_170_ap_return_0) < $signed(last_reg_135)? 1'b1: 1'b0);
assign tmp2_fu_349_p2 = (notlhs_fu_338_p2 & notrhs_fu_343_p2);
assign tmp_1_fu_328_p1 = $signed(grp_queue_fu_170_ap_return_1);
assign tmp_2_fu_257_p2 = (tmp_4_fu_251_p2 & tmp_fu_236_p2);
assign tmp_3_cast_fu_247_p1 = $unsigned(tmp_3_fu_241_p2);
assign tmp_3_fu_241_p2 = (ap_const_lv8_C7 - i_1_reg_100);
assign tmp_4_fu_251_p2 = (grp_queue_fu_170_ap_return_1 == tmp_3_cast_fu_247_p1? 1'b1: 1'b0);
assign tmp_6_fu_281_p1 = $unsigned(i_2_reg_112);
assign tmp_7_fu_355_p2 = (tmp2_fu_349_p2 & rev1_fu_333_p2);
assign tmp_9_fu_305_p1 = $unsigned(i_3_reg_124);
assign tmp_fu_236_p2 = (grp_queue_fu_170_ap_return_0 == i_1_cast5_reg_384? 1'b1: 1'b0);
always @ (posedge ap_clk)
begin
    current_priority_cast6_cast_reg_379[8] <= 1'b0;
    i_1_cast5_reg_384[31:8] <= 24'b000000000000000000000000;
end



endmodule //runTest

